"use client";

import { AlertTriangle, HelpCircle, TrendingUp, CheckCircle } from "lucide-react";

export default function InterpretPage() {
  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="flex justify-between items-center">
        <div>
           <h1 className="text-2xl font-bold text-gray-900">Interpretation & Reasoning</h1>
           <p className="text-gray-500 mt-1">AI-assisted analysis of key financial ratios.</p>
        </div>
        <div className="text-sm text-gray-400">
            Generated by Insight Engine v1.0
        </div>
      </div>

      {/* Company Summary */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
        <h2 className="text-xl font-semibold text-primary mb-4 flex items-center">
            <TrendingUp className="w-5 h-5 mr-2" />
            Company Summary
        </h2>
        <div className="prose prose-blue max-w-none text-gray-700">
            <p>
                The company operates as a leading manufacturer in the specialized electronics sector, characterized by <strong>high gross margins (24.5%)</strong> but significant working capital requirements. Recent shifts suggest a pivot towards higher R&D investment, impacting short-term net profitability.
            </p>
            <p className="mt-2">
                Primary value drivers include proprietary technology in semiconductor packaging and a robust supply chain network. Key risks involve raw material price volatility and high customer concentration in the consumer electronics segment.
            </p>
        </div>
      </div>

      <h3 className="text-lg font-bold text-gray-800 pt-4">Signal Analysis</h3>

      {/* Signal Card 1: High Cash, High Debt */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="border-l-4 border-signal-red">
            <div className="p-6 bg-red-50/30">
                <div className="flex items-center space-x-3 mb-4">
                    <AlertTriangle className="w-6 h-6 text-signal-red" />
                    <h3 className="text-lg font-bold text-gray-900">High Cash, High Debt</h3>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div>
                        <h4 className="font-semibold text-gray-800 mb-2 text-sm uppercase tracking-wide">What We See</h4>
                        <p className="text-gray-700 mb-4">
                            The company holds <span className="font-medium text-gray-900">¥1.2B in cash</span> while carrying <span className="font-medium text-gray-900">¥800M in short-term debt</span> at 8% interest.
                        </p>

                        <h4 className="font-semibold text-gray-800 mb-2 text-sm uppercase tracking-wide">Possible Explanations</h4>
                        <ul className="list-disc list-outside ml-5 space-y-1 text-gray-600">
                            <li>Cash is restricted (e.g., deposits for projects, regulatory requirements).</li>
                            <li>Cash is held in subsidiaries without upstream mobility.</li>
                            <li>Timing mismatch between capital raising and deployment.</li>
                            <li>Conservative liquidity management in uncertain environment.</li>
                        </ul>
                    </div>

                    <div className="bg-white p-5 rounded-lg border border-gray-100 shadow-sm">
                         <h4 className="font-semibold text-primary mb-3 text-sm uppercase tracking-wide flex items-center">
                            <HelpCircle className="w-4 h-4 mr-2" />
                            Diligence Questions
                         </h4>
                         <ul className="space-y-3">
                             <li className="flex items-start text-sm text-gray-700">
                                <span className="mr-2 text-primary">•</span>
                                What portion of cash is restricted? (Check notes)
                             </li>
                             <li className="flex items-start text-sm text-gray-700">
                                <span className="mr-2 text-primary">•</span>
                                Are there debt covenants limiting cash use?
                             </li>
                             <li className="flex items-start text-sm text-gray-700">
                                <span className="mr-2 text-primary">•</span>
                                What is the cash held at subsidiary vs. parent level?
                             </li>
                             <li className="flex items-start text-sm text-gray-700">
                                <span className="mr-2 text-primary">•</span>
                                Is there an upcoming large CapEx or M&A plan?
                             </li>
                         </ul>
                         
                         <div className="mt-6 pt-4 border-t border-gray-100">
                             <h5 className="text-xs font-bold text-gray-500 uppercase">Sector Benchmark</h5>
                             <p className="mt-1 text-sm text-gray-800">
                                Sector median: <span className="font-medium">2.5x</span> cash-to-debt ratio vs. this company's <span className="font-medium text-red-600">1.5x</span>.
                             </p>
                         </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

      {/* Signal Card 2: Strong Cash Flow (Green) */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="border-l-4 border-signal-green">
            <div className="p-6 bg-green-50/30">
                <div className="flex items-center space-x-3 mb-4">
                    <CheckCircle className="w-6 h-6 text-signal-green" />
                    <h3 className="text-lg font-bold text-gray-900">Strong Operating Cash Flow</h3>
                </div>
                <div className="prose prose-sm max-w-none text-gray-600">
                    <p>
                        Operating cash flow has consistently exceeded net income by 20% for the past 3 years, indicating high quality of earnings and strong cash conversion efficiency. This suggests the company is effectively managing its working capital.
                    </p>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
}
