"use client";

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "zh";

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    // Brand (Fixed)
    insightViewer: "Insight Viewer",

    // Common
    dashboard: "Dashboard",
    user: "User",
    settings: "Settings",
    loading: "Loading...",
    processing: "Processing...",
    error: "Error",
    warning: "Warning",
    success: "Success",
    clearCache: "Clear Cache",
    download: "Download",
    preview: "Preview",
    page: "Page",
    of: "of",
    periodsFound: "Periods Found",
    latestPeriod: "Latest Period",
    noData: "No Data",
    fetchData: "Fetch Data",
    search: "Search",
    annualOnly: "Annual Only",
    hideZeros: "Hide Zeros",
    sheet: "Sheet",
    items: "Items",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    metric: "Metric",
    current: "Current",
    previous: "Previous",
    diff: "Diff",
    target: "Target",
    yoy: "YoY",
    sequential: "Sequential",
    vs: "vs",
    unitMillionCNY: "Unit: Million CNY",
    note: "Note",
    source: "Source",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    remove: "Remove",
    browseFiles: "Browse Files",
    copiedToClipboard: "Copied to clipboard",

    // Navigation
    dataImport: "Data Import",
    dataExplorer: "Data Explorer",
    ratios: "Ratios",
    charts: "Charts",
    flags: "Flags",
    aiInsights: "AI Insights",
    reportGenerator: "Report Generator",

    // Home Page
    welcomeTitle: "Welcome to Insight Viewer",
    welcomeDesc:
      "Turn dense Chinese financial filings into readable, comparable, and actionable structures.",
    step1Title: "1. Upload",
    step1Desc:
      "Normalize financial data from various sources into a structured format.",
    step2Title: "2. Analyze",
    step2Desc:
      "View computed ratios, Key Financial Ratios, and visualize key trends.",
    step3Title: "3. Interpret",
    step3Desc: "Get AI-assisted insights and export comprehensive reports.",
    startAnalysis: "Start Analysis",

    // Import Page
    importTitle: "Data Import",
    importDesc: "Search by Stock Symbol or upload Excel/JSON files.",
    howToImport: "How to Import Data Correctly",
    howToImportStep1: "1. Search A-Share",
    howToImportStep1Desc: "For Chinese A-Share companies only.",
    howToImportStep1Bullet1: "Enter 6-digit code (e.g., 600519).",
    howToImportStep1Bullet2: "Set Start/End years (e.g., 2020-2023).",
    howToImportStep2: "2. Paste JSON",
    howToImportStep2Desc: "For structured data from LLMs.",
    howToImportStep2Bullet1: 'Use the "{copyLlmPrompt}" button.',
    howToImportStep2Bullet2: "Paste the prompt into DeepSeek/ChatGPT/Claude.",
    howToImportStep2Bullet3: "Upload your Excel/PDF/Image to the LLM.",
    howToImportStep2Bullet4: "Paste the JSON response here.",
    howToImportStep3: "3. Upload Excel",
    howToImportStep3Desc: "For custom financial models.",
    howToImportStep3Bullet1: "Download standard templates below.",
    howToImportStep3Bullet2:
      "Ensure header row has years (e.g., 2023 Annual, 2023 Q1, 2023-01).",
    searchAShare: "Search A-Share",
    searchAShareDesc: "For Chinese A-Share companies only.",
    pasteJson: "Paste JSON",
    pasteJsonDesc: "For structured data from LLMs.",
    uploadExcel: "Upload Excel",
    uploadExcelDesc: "For custom financial models.",
    dragDropTitle: "Drag & Drop Reports",
    dragDropDesc: "Drag and drop your Excel or JSON files here",
    selectedFiles: "Selected Files",
    parsing: "Parsing...",
    startProcessing: "Start Processing",
    copyLlmPrompt: "Copy LLM Prompt Template",
    loadProcessJson: "Load & Process JSON",
    addToExisting: "Add to existing data",
    fetchError: "Failed to fetch stock data",
    parseError: "Invalid JSON format",
    uploadError: "Upload failed",
    importWarnings: "Import Warnings",
    fileTypeRestricted:
      "File type is restricted to Excel (.xlsx, .xls) or JSON (.json) files.",
    stockCodeInvalid: "Stock Code must be a 6-digit number.",
    fetchGenericError: "An error occurred while fetching stock data.",
    processJsonError: "Failed to process pasted JSON",
    companyNameMismatch:
      "Cannot append data. Company name mismatch: Existing '{existing}' vs New '{new}'.",
    noReportDataInJson: "The pasted JSON is valid but contains no report data.",
    noValidReportsExtracted:
      "Could not extract any valid reports from the provided files.",
    checkFileFormat:
      "No valid data could be extracted. Please check the file format.",
    tushareNote: "Note: Requires Tushare API Token configured on backend.",
    copyWarnings: "Copy Warnings",
    warningDetails:
      "These rows were skipped because they did not match the template. Please review your file or the template.",
    llmPromptTemplate: `You are a strict data extraction assistant. Convert the provided financial report (Image/Text/Excel) into the following JSON structure. \nRules:\n1. Return ONLY valid JSON. No markdown formatting, no explanations.\n2. If a field is missing in the source, remove that corresponding item.\n3. Use the exact keys provided below.\n4. "fiscal_year" Format:\n   - Annual: "2023 Annual"\n   - Quarterly: "2023 Q1", "2023 Q2", etc.\n   - Monthly: "2023-01", "2023-02", etc.\n5. "period_type": "Annual", "Quarterly", or "Monthly".\n6. If the source contains multiple periods, generate a separate object in the "reports" array for EACH period.\n\nTemplate:\n{\n  "company_meta": {\n    "name": "Company Name Placeholder",\n    "stock_code": "000000",\n    "currency": "CNY"\n  },\n  "reports": [\n    {\n      "fiscal_year": "2023 Annual",\n      "period_type": "Annual",\n      "data": {\n        "income_statement": {\n          "title": "Income Statement",\n          "total_operating_revenue": {\n            "amount": 0.0,\n            "operating_revenue": 0.0,\n            "interest_income": 0.0,\n            "earned_premiums": 0.0,\n            "fee_and_commission_income": 0.0,\n            "other_business_revenue": 0.0,\n            "other_items": 0.0\n          },\n          "total_operating_cost": {\n            "amount": 0.0,\n            "operating_cost": 0.0,\n            "interest_expenses": 0.0,\n            "fee_and_commission_expenses": 0.0,\n            "taxes_and_surcharges": 0.0,\n            "selling_expenses": 0.0,\n            "admin_expenses": 0.0,\n            "rd_expenses": 0.0,\n            "financial_expenses": {\n              "amount": 0.0,\n              "interest_expenses": 0.0,\n              "interest_income": 0.0\n            },\n            "asset_impairment_loss": 0.0,\n            "credit_impairment_loss": 0.0,\n            "surrender_value": 0.0,\n            "net_compensation_expenses": 0.0,\n            "net_insurance_contract_reserves": 0.0,\n            "policy_dividend_expenses": 0.0,\n            "reinsurance_expenses": 0.0,\n            "other_business_costs": 0.0,\n            "other_items": 0.0\n          },\n          "other_operating_income": {\n            "amount": 0.0,\n            "fair_value_change_income": 0.0,\n            "investment_income": 0.0,\n            "investment_income_from_associates_jv": 0.0,\n            "net_exposure_hedging_income": 0.0,\n            "exchange_income": 0.0,\n            "asset_disposal_income": 0.0,\n            "asset_impairment_loss_new": 0.0,\n            "credit_impairment_loss_new": 0.0,\n            "other_income": 0.0,\n            "operating_profit_other_items": 0.0,\n            "operating_profit_balance_items": 0.0\n          },\n          "operating_profit": {\n            "amount": 0.0,\n            "non_operating_revenue": 0.0,\n            "non_current_asset_disposal_gain": 0.0,\n            "non_operating_expenses": 0.0,\n            "non_current_asset_disposal_loss": 0.0,\n            "other_items_affecting_total_profit": 0.0,\n            "total_profit_balance_items": 0.0\n          },\n          "total_profit": {\n            "amount": 0.0,\n            "income_tax": 0.0,\n            "unconfirmed_investment_loss": 0.0,\n            "other_items_affecting_net_profit": 0.0,\n            "net_profit_difference": 0.0\n          },\n          "net_profit": {\n            "amount": 0.0,\n            "net_profit_continuing_ops": 0.0,\n            "net_profit_discontinued_ops": 0.0,\n            "profit_from_merged_party_before_merger": 0.0,\n            "net_profit_attr_to_parent": 0.0,\n            "minority_interest_income": 0.0,\n            "net_profit_deducting_non_recurring": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0\n          },\n          "earnings_per_share": {\n            "basic_eps": 0.0,\n            "diluted_eps": 0.0\n          },\n          "other_comprehensive_income": {\n            "amount": 0.0,\n            "attr_to_parent": 0.0,\n            "attr_to_minority": 0.0\n          },\n          "total_comprehensive_income": {\n            "amount": 0.0,\n            "attr_to_parent": 0.0,\n            "attr_to_minority": 0.0,\n            "derecognition_income_amortized_cost": 0.0\n          }\n        },\n        "balance_sheet": {\n          "title": "Balance Sheet",\n          "current_assets": {\n            "monetary_funds": 0.0,\n            "clearing_settlement_funds": 0.0,\n            "lending_funds": 0.0,\n            "funds_lent": 0.0,\n            "trading_financial_assets": 0.0,\n            "financial_assets_fvpl": {\n              "amount": 0.0,\n              "trading_financial_assets": 0.0,\n              "designated_financial_assets_fvpl": 0.0\n            },\n            "derivative_financial_assets": 0.0,\n            "notes_and_accounts_receivable": {\n              "amount": 0.0,\n              "notes_receivable": 0.0,\n              "accounts_receivable": 0.0\n            },\n            "receivables_financing": 0.0,\n            "prepayments": 0.0,\n            "premiums_receivable": 0.0,\n            "reinsurance_accounts_receivable": 0.0,\n            "reinsurance_contract_reserves_receivable": 0.0,\n            "other_receivables_total": {\n              "amount": 0.0,\n              "interest_receivable": 0.0,\n              "dividends_receivable": 0.0,\n              "other_receivables": 0.0\n            },\n            "export_tax_refund_receivable": 0.0,\n            "subsidies_receivable": 0.0,\n            "internal_receivables": 0.0,\n            "buy_back_financial_assets": 0.0,\n            "financial_assets_amortized_cost": 0.0,\n            "inventories": 0.0,\n            "financial_assets_fvoci": 0.0,\n            "contract_assets": 0.0,\n            "assets_held_for_sale": 0.0,\n            "non_current_assets_due_within_1y": 0.0,\n            "agency_business_assets": 0.0,\n            "other_current_assets": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_current_assets": 0.0\n          },\n          "non_current_assets": {\n            "loans_and_advances": 0.0,\n            "debt_investments": 0.0,\n            "other_debt_investments": 0.0,\n            "financial_assets_amortized_cost_non_current": 0.0,\n            "financial_assets_fvoci_non_current": 0.0,\n            "available_for_sale_financial_assets": 0.0,\n            "held_to_maturity_investments": 0.0,\n            "long_term_receivables": 0.0,\n            "long_term_equity_investments": 0.0,\n            "investment_properties": 0.0,\n            "fixed_assets": 0.0,\n            "construction_in_progress": 0.0,\n            "construction_materials": 0.0,\n            "other_equity_instrument_investments": 0.0,\n            "other_non_current_financial_assets": 0.0,\n            "fixed_assets_liquidation": 0.0,\n            "productive_biological_assets": 0.0,\n            "oil_and_gas_assets": 0.0,\n            "right_of_use_assets": 0.0,\n            "intangible_assets": 0.0,\n            "balance_items": 0.0,\n            "development_expenses": 0.0,\n            "goodwill": 0.0,\n            "long_term_deferred_expenses": 0.0,\n            "deferred_tax_assets": 0.0,\n            "other_non_current_assets": 0.0,\n            "other_items": 0.0,\n            "total_non_current_assets": 0.0\n          },\n          "assets_summary": {\n            "other_asset_items": 0.0,\n            "asset_balance_items": 0.0,\n            "total_assets": 0.0\n          },\n          "current_liabilities": {\n            "short_term_borrowings": 0.0,\n            "borrowings_from_central_bank": 0.0,\n            "deposits_and_interbank_placements": 0.0,\n            "borrowings_from_interbank": 0.0,\n            "trading_financial_liabilities": 0.0,\n            "financial_liabilities_fvpl": {\n              "amount": 0.0,\n              "trading_financial_liabilities": 0.0,\n              "designated_financial_liabilities_fvpl": 0.0\n            },\n            "derivative_financial_liabilities": 0.0,\n            "notes_and_accounts_payable": {\n              "amount": 0.0,\n              "notes_payable": 0.0,\n              "accounts_payable": 0.0\n            },\n            "advances_from_customers": 0.0,\n            "contract_liabilities": 0.0,\n            "sell_buy_back_financial_assets": 0.0,\n            "fees_and_commissions_payable": 0.0,\n            "payroll_payable": 0.0,\n            "taxes_payable": 0.0,\n            "other_payables_total": {\n              "amount": 0.0,\n              "interest_payable": 0.0,\n              "dividends_payable": 0.0,\n              "other_payables": 0.0\n            },\n            "reinsurance_accounts_payable": 0.0,\n            "internal_payables": 0.0,\n            "estimated_current_liabilities": 0.0,\n            "insurance_contract_reserves": 0.0,\n            "acting_trading_securities": 0.0,\n            "acting_underwriting_securities": 0.0,\n            "deferred_revenue_within_1y": 0.0,\n            "financial_liabilities_amortized_cost": 0.0,\n            "short_term_bonds_payable": 0.0,\n            "liabilities_held_for_sale": 0.0,\n            "non_current_liabilities_due_within_1y": 0.0,\n            "agency_business_liabilities": 0.0,\n            "other_current_liabilities": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_current_liabilities": 0.0\n          },\n          "non_current_liabilities": {\n            "long_term_borrowings": 0.0,\n            "financial_liabilities_amortized_cost_non_current": 0.0,\n            "bonds_payable": {\n              "amount": 0.0,\n              "preference_shares": 0.0,\n              "perpetual_bonds": 0.0\n            },\n            "lease_liabilities": 0.0,\n            "long_term_payables": 0.0,\n            "long_term_payroll_payable": 0.0,\n            "special_payables": 0.0,\n            "estimated_liabilities": 0.0,\n            "deferred_revenue": 0.0,\n            "deferred_tax_liabilities": 0.0,\n            "other_non_current_liabilities": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_non_current_liabilities": 0.0\n          },\n          "liabilities_summary": {\n            "other_liability_items": 0.0,\n            "liability_balance_items": 0.0,\n            "total_liabilities": 0.0\n          },\n          "equity": {\n            "title": "Owner's Equity",\n            "paid_in_capital": 0.0,\n            "other_equity_instruments": {\n              "amount": 0.0,\n              "preference_shares": 0.0,\n              "perpetual_bonds": 0.0,\n              "other": 0.0\n            },\n            "capital_reserves": 0.0,\n            "other_comprehensive_income": 0.0,\n            "treasury_stock": 0.0,\n            "special_reserves": 0.0,\n            "surplus_reserves": 0.0,\n            "general_risk_reserves": 0.0,\n            "unconfirmed_investment_loss": 0.0,\n            "undistributed_profit": 0.0,\n            "proposed_cash_dividends": 0.0,\n            "currency_translation_diff": 0.0,\n            "parent_equity_other_items": 0.0,\n            "parent_equity_balance_items": 0.0,\n            "total_parent_equity": 0.0,\n            "minority_interests": 0.0,\n            "equity_other_items": 0.0,\n            "equity_balance_items": 0.0,\n            "total_equity": 0.0\n          },\n          "balance_check": {\n            "liabilities_and_equity_other_items": 0.0,\n            "liabilities_and_equity_balance_items": 0.0,\n            "total_liabilities_and_equity": 0.0\n          }\n        },\n        "cash_flow_statement": {\n          "title": "Cash Flow Statement",\n          "operating_activities": {\n            "cash_received_from_goods_and_services": 0.0,\n            "net_increase_deposits_interbank": 0.0,\n            "net_increase_borrowings_central_bank": 0.0,\n            "net_increase_borrowings_other_financial": 0.0,\n            "cash_received_original_premiums": 0.0,\n            "net_cash_received_reinsurance": 0.0,\n            "net_increase_insured_investment": 0.0,\n            "net_increase_disposal_trading_assets": 0.0,\n            "cash_received_interest_commission": 0.0,\n            "net_increase_borrowed_funds": 0.0,\n            "net_decrease_loans_advances": 0.0,\n            "net_increase_repurchase_funds": 0.0,\n            "tax_refunds_received": 0.0,\n            "other_cash_received_operating": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_operating": 0.0,\n            "cash_paid_for_goods_and_services": 0.0,\n            "net_increase_loans_advances": 0.0,\n            "net_increase_deposits_central_bank_interbank": 0.0,\n            "cash_paid_original_contract_claims": 0.0,\n            "cash_paid_interest_commission": 0.0,\n            "cash_paid_policy_dividends": 0.0,\n            "cash_paid_to_employees": 0.0,\n            "taxes_paid": 0.0,\n            "other_cash_paid_operating": 0.0,\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_operating": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_operating": 0.0\n          },\n          "investing_activities": {\n            "cash_received_from_investment_recovery": 0.0,\n            "cash_received_from_investment_income": 0.0,\n            "net_cash_from_disposal_assets": 0.0,\n            "net_cash_from_disposal_subsidiaries": 0.0,\n            "cash_received_from_pledge_deposit_reduction": 0.0,\n            "other_cash_received_investing": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_investing": 0.0,\n            "cash_paid_for_assets": 0.0,\n            "cash_paid_for_investments": 0.0,\n            "net_increase_pledged_loans": 0.0,\n            "net_cash_paid_subsidiaries": 0.0,\n            "cash_paid_for_pledge_deposit_increase": 0.0,\n            "other_cash_paid_investing": 0.0,\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_investing": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_investing": 0.0\n          },\n          "financing_activities": {\n            "cash_received_from_investments": {\n              "amount": 0.0,\n              "from_minority_shareholders": 0.0\n            },\n            "cash_received_from_borrowings": 0.0,\n            "cash_received_from_bond_issue": 0.0,\n            "other_cash_received_financing": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_financing": 0.0,\n            "cash_paid_for_debt_repayment": 0.0,\n            "cash_paid_for_dividends_and_profits": 0.0,\n            "dividends_paid_to_minority": 0.0,\n            "cash_paid_for_minority_equity": 0.0,\n            "other_cash_paid_financing": {\n              "amount": 0.0,\n              "paid_to_minority_for_capital_reduction": 0.0\n            },\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_financing": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_financing": 0.0\n          },\n          "cash_increase": {\n            "exchange_rate_effect": 0.0,\n            "increase_other_items": 0.0,\n            "increase_balance_items": 0.0,\n            "net_increase_cash_and_equivalents": 0.0,\n            "cash_at_beginning": 0.0,\n            "end_balance_other_items": 0.0,\n            "end_balance_balance_items": 0.0,\n            "cash_at_end": 0.0\n          },\n          "supplementary_info": {\n            "net_profit_adjustment": {\n              "net_profit": 0.0,\n              "asset_impairment_reserves": 0.0,\n              "depreciation_fixed_assets_investment_props": 0.0,\n              "depreciation_others": 0.0,\n              "depreciation_investment_props": 0.0,\n              "amortization_intangible_assets": 0.0,\n              "amortization_long_term_deferred": 0.0,\n              "amortization_deferred_revenue": 0.0,\n              "decrease_deferred_expenses": 0.0,\n              "increase_accrued_expenses": 0.0,\n              "loss_disposal_assets": 0.0,\n              "loss_scrapping_assets": 0.0,\n              "loss_fair_value_change": 0.0,\n              "financial_expenses": 0.0,\n              "investment_loss": 0.0,\n              "deferred_tax": 0.0,\n              "decrease_deferred_tax_assets": 0.0,\n              "increase_deferred_tax_liabilities": 0.0,\n              "increase_estimated_liabilities": 0.0,\n              "decrease_inventories": 0.0,\n              "decrease_operating_receivables": 0.0,\n              "increase_operating_payables": 0.0,\n              "other": 0.0,\n              "net_cash_flow_other_items": 0.0,\n              "net_cash_flow_balance_items": 0.0,\n              "net_cash_flow_from_operating_indirect": 0.0\n            },\n            "significant_non_cash": {\n              "debt_to_capital": 0.0,\n              "convertible_bonds_due_within_1y": 0.0,\n              "fixed_assets_finance_lease": 0.0,\n              "non_cash_items_other": 0.0\n            },\n            "cash_change_check": {\n              "cash_end_balance": 0.0,\n              "cash_begin_balance": 0.0,\n              "equivalents_end_balance": 0.0,\n              "equivalents_begin_balance": 0.0,\n              "net_increase_other": 0.0,\n              "net_increase_balance": 0.0,\n              "net_increase_cash_and_equivalents_indirect": 0.0\n            },\n            "credit_impairment_loss": 0.0\n          }\n        }\n      }\n    }\n  ]\n}`,

    // Explorer Page
    explorerTitle: "Financial Data Explorer",
    noDataFound: "No Data Found",
    getFinancialData: "Get Financial Data",
    lineItem: "Line Item",
    type: "Type",
    incomeStatement: "Income Statement",
    balanceSheet: "Balance Sheet",
    cashFlowStatement: "Cash Flow Statement",
    showingRecords: "Showing records",
    zerosHidden: "Zeros Hidden",

    // Ratios Page
    ratiosTitle: "Financial Ratios",
    ratiosDesc: "Advanced financial performance metrics and ratio analysis.",
    comparisonMode: "Comparison Mode",
    dupontIdentity: "DuPont Identity (ROE Decomposition)",
    roeFormula: "ROE = Net Margin × Asset Turnover × Fin. Leverage",
    returnOnEquity: "Return on Equity",
    ownerValueCreation: "Owner Value Creation",
    profitability: "Profitability",
    efficiency: "Efficiency",
    leverage: "Leverage",
    netMargin: "Net Margin",
    assetTurnover: "Asset Turnover",
    equityMultiplier: "Equity Multiplier",
    profitabilityMargins: "Profitability & Margins",
    returnOnInvestment: "Return on Investment",
    solvencyLiquidity: "Solvency & Liquidity",
    operatingEfficiency: "Operating Efficiency",
    cashFlowQuality: "Cash Flow Quality",
    growthIndicators: "Growth Indicators",
    analyzing: "Analyzing",
    standardizedAnalysis: "Standardized Financial Analysis",

    // Charts Page
    chartsTitle: "Financial Charts",
    chartsDesc: "Visual analysis of financial structure and performance.",
    profitabilityTrends: "Profitability Trends",
    liquidityCycle: "Liquidity & Cycle Analysis",
    efficiencyCost: "Efficiency & Cost Structure",
    cashFlowGrowth: "Cash Flow & Growth",
    structureAnalysis: "Structure Analysis",
    returnMetrics: "Return Metrics (%)",
    revenueVsCash: "Revenue vs Cash Collection",
    netProfitVsOCF: "Net Profit vs Operating Cash Flow",
    profitSources: "Profit Sources Breakdown",
    liquidityRatios: "Liquidity Ratios Trend",
    workingCapitalCycle: "Working Capital Cycle (Days)",
    debtToAsset: "Debt-to-Asset Ratio & Delta",
    turnoverRatios: "Turnover Ratios",
    costStructure: "Cost & Expense Structure (%)",
    cashFlowSummary: "Cash Flow Summary",
    ocfCapexFcf: "OCF vs Capex vs FCF Trend",
    revenueGrowth: "Revenue Growth",
    netProfitGrowth: "Net Profit Growth",
    assetStructure: "Asset Structure",
    liabilityStructure: "Liability Structure",
    equityStructure: "Equity Structure",

    // Chart Data Keys
    ROE: "ROE",
    "Net Margin": "Net Margin",
    "Gross Margin": "Gross Margin",
    Revenue: "Revenue",
    "Cash From Sales": "Cash From Sales",
    "Net Profit": "Net Profit",
    "Operating CF": "Operating CF",
    "Main Business Profit": "Main Business Profit",
    "Finance Expense": "Finance Expense",
    "Impairment Loss": "Impairment Loss",
    "Fair Value Change": "Fair Value Change",
    "Investment Income": "Investment Income",
    "Asset Disposal": "Asset Disposal",
    "Other Income": "Other Income",
    "Non-op Revenue": "Non-op Revenue",
    "Non-op Expense": "Non-op Expense",
    "Current Ratio": "Current Ratio",
    "Quick Ratio": "Quick Ratio",
    "Cash Ratio": "Cash Ratio",
    DIO: "DIO",
    DSO: "DSO",
    DPO: "DPO",
    CCC: "CCC",
    "Debt Ratio": "Debt Ratio",
    "Debt Ratio Delta": "Debt Ratio Delta",
    "Inventory Turnover": "Inventory Turnover",
    "AR Turnover": "AR Turnover",
    "Fixed Asset Turnover": "Fixed Asset Turnover",
    "Total Asset Turnover": "Total Asset Turnover",
    COGS: "COGS",
    "Tax & Surcharge": "Tax & Surcharge",
    "Selling Exp": "Selling Exp",
    "Admin Exp": "Admin Exp",
    "R&D Exp": "R&D Exp",
    "Main Profit": "Main Profit",
    "Investing CF": "Investing CF",
    "Financing CF": "Financing CF",
    Capex: "Capex",
    "Free CF": "Free CF",
    "Revenue Growth": "Revenue Growth",
    "Net Profit Growth": "Net Profit Growth",
    "Cash & Equiv Etc": "Cash & Equiv Etc",
    "Receivables Etc": "Receivables Etc",
    Prepayments: "Prepayments",
    Inventory: "Inventory",
    "Other Current Assets": "Other Current Assets",
    "Long-term Equity Invest": "Long-term Equity Invest",
    Goodwill: "Goodwill",
    "Fixed Assets": "Fixed Assets",
    "Construction In Progress": "Construction In Progress",
    "Right-of-use Assets": "Right-of-use Assets",
    "Intangible Assets": "Intangible Assets",
    "Other Assets": "Other Assets",
    "Interest-bearing Debt": "Interest-bearing Debt",
    "Payables Etc": "Payables Etc",
    "Prepayments Received Etc": "Prepayments Received Etc",
    "Payroll Payable Etc": "Payroll Payable Etc",
    "Taxes Payable": "Taxes Payable",
    "Other Payables": "Other Payables",
    "Lease Liabilities": "Lease Liabilities",
    "Long-term Payables": "Long-term Payables",
    "Other Liabilities": "Other Liabilities",
    "Paid-in Capital": "Paid-in Capital",
    "Other Equity Instruments": "Other Equity Instruments",
    "Capital Reserves": "Capital Reserves",
    "Other Comprehensive Income": "Other Comprehensive Income",
    "Treasury Stock": "Treasury Stock",
    "Special Reserves": "Special Reserves",
    "Surplus Reserves": "Surplus Reserves",
    "Undistributed Profit": "Undistributed Profit",
    // Metric Descriptions
    grossMarginDesc: "Gross Profit / Revenue",
    netProfitMarginDesc: "Net Income / Revenue",
    costOfSalesRatioDesc: "COGS / Revenue",
    expenseOfSalesRatioDesc: "Operating Expenses / Revenue",
    ebitMarginDesc: "EBIT / Revenue",
    operatingMarginDesc: "Operating Income / Revenue",
    assetImpairmentRatioDesc: "Asset Impairment / Revenue",
    roaDesc: "Return on Assets",
    roicDesc: "Return on Invested Capital",
    cfroiProxyDesc: "Cash Flow Return on Investment",
    croicDesc: "Cash Return on Invested Capital",
    currentRatioDesc: "Current Assets / Current Liabilities",
    quickRatioDesc: "Quick Assets / Current Liabilities",
    cashRatioDesc: "Cash / Current Liabilities",
    debtToAssetsDesc: "Total Debt / Total Assets",
    debtToEquityDesc: "Total Debt / Total Equity",
    interestCoverageDesc: "EBIT / Interest Expense",
    proxyInterestRateDesc: "Est. Interest Rate on Debt",
    operatingCashFlowRatioDesc: "OCF / Current Liabilities",
    nwcToAssetsDesc: "Net Working Capital / Total Assets",
    netDebtDesc: "Total Debt - Cash",
    sellingExpenseRatioDesc: "Selling Exp / Revenue",
    adminExpenseRatioDesc: "Admin Exp / Revenue",
    rdExpenseRatioDesc: "R&D Exp / Revenue",
    inventoryTurnoverDesc: "COGS / Avg Inventory",
    daysInventoryOutstandingDesc: "Days to sell inventory",
    arTurnoverDesc: "Revenue / Avg AR",
    daysSalesOutstandingDesc: "Days to collect receivables",
    totalAssetTurnoverDesc: "Revenue / Avg Total Assets",
    operatingCycleDesc: "DIO + DSO",
    cashConversionCycleDesc: "DIO + DSO - DPO",
    workingCapitalDesc: "Current Assets - Current Liabilities",
    ocfToRevenueDesc: "OCF / Revenue",
    ocfToOperatingIncomeDesc: "OCF / Operating Income",
    freeCashFlowDesc: "Operating Cash Flow - Capex",
    cashCollectionRatioDesc: "Cash from Sales / Revenue",
    ocfToDebtDesc: "OCF / Total Debt",
    ocfToCapexDesc: "OCF / Capital Expenditures",
    revenueGrowthDesc: "YoY Revenue Growth",
    netProfitGrowthDesc: "YoY Net Profit Growth",
    ocfGrowthDesc: "YoY OCF Growth",
    requiresPrevPeriodData: "Requires previous period data",

    // Flags Page
    flagsTitle: "Flag Checklist",
    flagsDesc: "Automated forensic checks based on financial data.",
    riskIndicators: "Risk Indicators",
    healthSignals: "Health Signals",
    additionalData: "Additional Data Required",
    noFlags: "No Significant Flags Detected",
    noFlagsDesc:
      "The automated analysis did not find any extreme outliers matching the standard risk or health criteria.",
    triggerCondition: "Trigger Condition",
    targetCriteria: "Target Criteria",
    logic: "Logic",
    risks: "Risks",
    health: "Health",
    check: "Check",

    // Flag Categories
    Liquidity: "Liquidity",
    Revenue: "Revenue",
    Cost: "Cost",
    Asset: "Asset",
    Debt: "Debt",
    Earnings: "Earnings",
    Growth: "Growth",

    // Flag Names
    "Abnormal Gross Margin Expansion": "Abnormal Gross Margin Expansion",
    "Inventory Divergence": "Inventory Divergence",
    "High Cash Interest Rate": "High Cash Interest Rate",
    "Inverted Interest Rate": "Inverted Interest Rate",
    "High-Cash, High-Debt": "High-Cash, High-Debt",
    "Asset Disposal Reliance": "Asset Disposal Reliance",
    "Asset Impairment Surge": "Asset Impairment Surge",
    "Credit Impairment Surge": "Credit Impairment Surge",
    "Non-Operating Rev Dependency": "Non-Operating Rev Dependency",
    "Fair Value Reliance": "Fair Value Reliance",
    "Investment Income Reliance": "Investment Income Reliance",
    "Other Income Reliance": "Other Income Reliance",
    "Accounts Receivable Bloat": "Accounts Receivable Bloat",
    "Excessive Inventory": "Excessive Inventory",
    "Other Receivables Anomaly": "Other Receivables Anomaly",
    "Goodwill Risk": "Goodwill Risk",
    "CIP Trap": "CIP Trap",
    "Deferred Expense Bloat": "Deferred Expense Bloat",
    "Other Payables Anomaly": "Other Payables Anomaly",
    "Selling Expense Efficiency": "Selling Expense Efficiency",
    "Admin Expense Divergence": "Admin Expense Divergence",
    "Prepayment Surge": "Prepayment Surge",
    "Payables Gap": "Payables Gap",
    "Other Cash Received Anomaly": "Other Cash Received Anomaly",
    "Cash-Backed Profits": "Cash-Backed Profits",
    "Self-Funding": "Self-Funding",
    "Conservative Leverage": "Conservative Leverage",
    "Cash-Profit Divergence": "Cash-Profit Divergence",
    "Low OCF/NI Ratio": "Low OCF/NI Ratio",
    "Rising DSO": "Rising DSO",
    "High Total Accruals": "High Total Accruals",
    "Debt Cliff": "Debt Cliff",
    "Margin Divergence": "Margin Divergence",
    "Negative FCF": "Negative FCF",
    "Payables Stretch": "Payables Stretch",

    // Flag Descriptions
    "Rising margins with slowing inventory turnover suggests potential earnings inflation via capitalization or failure to write down obsolete goods.":
      "Rising margins with slowing inventory turnover suggests potential earnings inflation via capitalization or failure to write down obsolete goods.",
    "Inventory growing significantly faster than sales suggests falling demand, obsolescence, or channel stuffing.":
      "Inventory growing significantly faster than sales suggests falling demand, obsolescence, or channel stuffing.",
    "Paying an excessively high rate on debt (or dividends included) can signal high-risk borrowing status.":
      "Paying an excessively high rate on debt (or dividends included) can signal high-risk borrowing status.",
    "Extremely low yield on cash balances suggests funds may be restricted, pledged, or non-existent.":
      "Extremely low yield on cash balances suggests funds may be restricted, pledged, or non-existent.",
    "Coexistence of high cash coverage and high debt/leverage, often indicating restricted or fictitious cash.":
      "Coexistence of high cash coverage and high debt/leverage, often indicating restricted or fictitious cash.",
    "Relying on selling assets to generate profit is unsustainable and masks core business weakness.":
      "Relying on selling assets to generate profit is unsustainable and masks core business weakness.",
    "Large write-downs ('Big Bath') indicate inflated past earnings or clearing decks for future.":
      "Large write-downs ('Big Bath') indicate inflated past earnings or clearing decks for future.",
    "Sharp deterioration in receivables quality, suggesting customer defaults.":
      "Sharp deterioration in receivables quality, suggesting customer defaults.",
    "Earnings driven by grants/fines rather than operations are low quality.":
      "Earnings driven by grants/fines rather than operations are low quality.",
    "Profits driven by paper gains are risky and don't reflect cash generation.":
      "Profits driven by paper gains are risky and don't reflect cash generation.",
    "Reliance on trading stocks or subsidiaries rather than main product.":
      "Reliance on trading stocks or subsidiaries rather than main product.",
    "Profit derived from 'Other Income' is often non-persistent.":
      "Profit derived from 'Other Income' is often non-persistent.",
    "Receivables growing faster than sales signals channel stuffing or relaxed credit terms.":
      "Receivables growing faster than sales signals channel stuffing or relaxed credit terms.",
    "Inventory growing faster than sales often signals potential write-downs.":
      "Inventory growing faster than sales often signals potential write-downs.",
    "Hiding place for misappropriated funds or loans to shareholders.":
      "Hiding place for misappropriated funds or loans to shareholders.",
    "High goodwill suggests aggressive acquisitions; risk of massive write-offs.":
      "High goodwill suggests aggressive acquisitions; risk of massive write-offs.",
    "CIP that doesn't convert to fixed assets may be capitalized expense or fraud.":
      "CIP that doesn't convert to fixed assets may be capitalized expense or fraud.",
    "Used to hide current expenses to artificially boost profits.":
      "Used to hide current expenses to artificially boost profits.",
    "Can hide off-book loans or illicit financing.":
      "Can hide off-book loans or illicit financing.",
    "Revenue skyrocketing while marketing costs stay flat is highly suspicious.":
      "Revenue skyrocketing while marketing costs stay flat is highly suspicious.",
    "Admin costs growing much faster than sales indicates inefficiency or unchecked compensation.":
      "Admin costs growing much faster than sales indicates inefficiency or unchecked compensation.",
    "Massive prepayments are common vehicles for embezzlement or fund transfer.":
      "Massive prepayments are common vehicles for embezzlement or fund transfer.",
    "Excessive payables growth signals liquidity stress—suppliers are funding the company.":
      "Excessive payables growth signals liquidity stress—suppliers are funding the company.",
    "Often used to hide non-operating cash to inflate OCF.":
      "Often used to hide non-operating cash to inflate OCF.",
    "Operating Cash Flow exceeds Total Net Profit, indicating high quality of earnings for the consolidated group.":
      "Operating Cash Flow exceeds Total Net Profit, indicating high quality of earnings for the consolidated group.",
    "The company generates enough cash to fully fund its capital expenditures and growth.":
      "The company generates enough cash to fully fund its capital expenditures and growth.",
    "Debt levels are low relative to earnings, indicating a strong balance sheet.":
      "Debt levels are low relative to earnings, indicating a strong balance sheet.",
    "Total profits are growing rapidly while cash flow is stagnant or falling, indicating low quality earnings.":
      "Total profits are growing rapidly while cash flow is stagnant or falling, indicating low quality earnings.",
    "Operating cash flow is significantly lower than reported total net income.":
      "Operating cash flow is significantly lower than reported total net income.",
    "It is taking significantly longer to collect payment from customers.":
      "It is taking significantly longer to collect payment from customers.",
    "Earnings are driven heavily by non-cash accruals rather than cash flow.":
      "Earnings are driven heavily by non-cash accruals rather than cash flow.",
    "Reliance on short-term debt exposes the company to refinancing risks.":
      "Reliance on short-term debt exposes the company to refinancing risks.",
    "Gross margin improved but Operating margin declined, suggesting rising overheads or expense reclassification.":
      "Gross margin improved but Operating margin declined, suggesting rising overheads or expense reclassification.",
    "Free Cash Flow has been negative for consecutive periods despite any reported profits.":
      "Free Cash Flow has been negative for consecutive periods despite any reported profits.",
    "Days Payable Outstanding increased significantly, potentially delaying payments to suppliers to boost cash.":
      "Days Payable Outstanding increased significantly, potentially delaying payments to suppliers to boost cash.",

    // Insights Page
    aiInsightsTitle: "AI Insights",
    aiInsightsDesc:
      "AI-assisted analysis of key financial ratios and anomalies.",
    aiModel: "AI Model",
    dataContext: "Data Context",
    generateInsights: "Generate Insights",
    analyzingSpinner: "Analyzing...",
    synthesizing: "Synthesizing Financial Narrative...",
    connectingTo: "Connecting to model...",
    noAnalysis: "No Analysis Generated Yet",
    clickToGenerate: 'Click "Generate Insights" to start the analysis.',
    downloadMD: "Download MD",
    modelGemini: "Google Gemini (Balanced)",
    modelDeepseek: "DeepSeek R1 (Forensic)",
    modelQwen: "Alibaba Qwen (CN Context)",

    // Report Page
    reportTitle: "Report Generator",
    exportSettings: "Export Settings",
    format: "Format",
    includeSections: "Include Sections",
    downloadPDF: "Download PDF",
    downloadMarkdown: "Download Markdown",
    companySummary: "Company Summary",
    financialMetrics: "Financial Metrics",
    chartsVisuals: "Charts & Visuals",
    signalAnalysis: "Signal Analysis",
    rawDataAppendix: "Raw Data Appendix",
    generatedOn: "Generated on",
    generatedVia: "Generated via",
    executiveSummary: "Executive Summary",
    mockReportTitle: "Financial Analysis Report",
    mockExecSummaryText:
      "The company shows strong top-line resilience with revenue holding steady at ¥2.39B. However, profitability signals suggest a need for closer inspection of operating expenses. Working capital efficiency remains a key strength.",
    mockSignalTriggered:
      "Triggered due to simultaneous high cash balance (¥1.2B) and short-term debt load.",
  },
  zh: {
    // Brand (Fixed)
    insightViewer: "Insight Viewer",

    // Common
    dashboard: "仪表板",
    user: "用户",
    settings: "设置",
    loading: "加载中...",
    processing: "处理中...",
    error: "错误",
    warning: "警告",
    success: "成功",
    clearCache: "清除缓存",
    download: "下载",
    preview: "预览",
    page: "页",
    of: "/",
    periodsFound: "发现周期数",
    latestPeriod: "最新周期",
    noData: "暂无数据",
    fetchData: "获取数据",
    search: "搜索",
    annualOnly: "仅显示年报",
    hideZeros: "隐藏零值",
    sheet: "报表",
    items: "项目",
    selectAll: "全选",
    deselectAll: "取消全选",
    metric: "指标",
    current: "当前",
    previous: "上期",
    diff: "变动",
    target: "目标",
    yoy: "同比",
    sequential: "环比",
    vs: "vs",
    unitMillionCNY: "单位：百万元 (CNY)",
    note: "注意",
    source: "来源",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    remove: "移除",
    browseFiles: "浏览文件",
    copiedToClipboard: "已复制到剪贴板",

    // Navigation
    dataImport: "数据导入",
    dataExplorer: "数据浏览",
    ratios: "财务比率",
    charts: "图表分析",
    flags: "风险标记",
    aiInsights: "AI 洞察",
    reportGenerator: "报告生成",

    // Home Page
    welcomeTitle: "欢迎使用 Insight Viewer",
    welcomeDesc:
      "将复杂的中文财务报告转化为清晰、可比且具有行动意义的结构化数据。",
    step1Title: "1. 上传",
    step1Desc: "将来自不同来源的财务数据标准化为统一结构。",
    step2Title: "2. 分析",
    step2Desc: "查看计算出的财务比率，关键指标，并可视化关键趋势。",
    step3Title: "3. 解读",
    step3Desc: "获取 AI 辅助的洞察分析并导出全面报告。",
    startAnalysis: "开始分析",

    // Import Page
    importTitle: "数据导入",
    importDesc: "通过股票代码搜索或上传 Excel/JSON 文件。",
    howToImport: "如何正确导入数据",
    howToImportStep1: "1. 搜索 A 股",
    howToImportStep1Desc: "仅限中国 A 股公司。",
    howToImportStep1Bullet1: "输入 6 位股票代码（如：600519）。",
    howToImportStep1Bullet2: "设置开始/结束年份（如：2020-2023）。",
    howToImportStep2: "2. 粘贴 JSON",
    howToImportStep2Desc: "用于 LLM 生成的结构化数据。",
    howToImportStep2Bullet1: "使用“{copyLlmPrompt}”按钮。",
    howToImportStep2Bullet2: "将提示词粘贴到 DeepSeek/Kimi/Qwen",
    howToImportStep2Bullet3: "将您的 Excel/PDF/图片上传给 LLM。",
    howToImportStep2Bullet4: "将生成的 JSON 响应粘贴到此处。",
    howToImportStep3: "3. 上传 Excel",
    howToImportStep3Desc: "用于自定义财务模型。",
    howToImportStep3Bullet1: "在下方下载标准模板。",
    howToImportStep3Bullet2:
      "确保表头行包含年份（如：2023 Annual, 2023 Q1, 2023-01）。",
    searchAShare: "搜索 A 股",
    searchAShareDesc: "仅限中国 A 股公司。",
    pasteJson: "粘贴 JSON",
    pasteJsonDesc: "用于 LLM 生成的结构化数据。",
    uploadExcel: "上传 Excel",
    uploadExcelDesc: "用于自定义财务模型。",
    dragDropTitle: "拖拽上传报表",
    dragDropDesc: "将 Excel 或 JSON 文件拖拽到此处",
    selectedFiles: "已选文件",
    parsing: "解析中...",
    startProcessing: "开始处理",
    copyLlmPrompt: "复制 LLM 提示词模板",
    loadProcessJson: "加载并处理 JSON",
    addToExisting: "添加到现有数据",
    fetchError: "获取股票数据失败",
    parseError: "JSON 格式无效",
    uploadError: "上传失败",
    importWarnings: "导入警告",
    fileTypeRestricted: "文件类型仅限 Excel (.xlsx, .xls) 或 JSON (.json)。",
    stockCodeInvalid: "股票代码必须是 6 位数字。",
    fetchGenericError: "获取股票数据时发生错误。",
    processJsonError: "处理粘贴的 JSON 失败。",
    companyNameMismatch:
      "无法追加数据。公司名称不匹配：现有 '{existing}' vs 新增 '{new}'。",
    noReportDataInJson: "粘贴的 JSON 有效，但未包含报告数据。",
    noValidReportsExtracted: "无法从提供的文件中提取任何有效报告。",
    checkFileFormat: "未能提取有效数据。请检查文件格式。",
    tushareNote: "注意：需要后端配置 Tushare API Token。",
    copyWarnings: "复制警告",
    warningDetails: "这些行因为不匹配模板而被跳过。请检查您的文件或模板。",
    llmPromptTemplate: `You are a strict data extraction assistant. Convert the provided financial report (Image/Text/Excel) into the following JSON structure. \nRules:\n1. Return ONLY valid JSON. No markdown formatting, no explanations.\n2. If a field is missing in the source, remove that corresponding item.\n3. Use the exact keys provided below.\n4. "fiscal_year" Format:\n   - Annual: "2023 Annual"\n   - Quarterly: "2023 Q1", "2023 Q2", etc.\n   - Monthly: "2023-01", "2023-02", etc.\n5. "period_type": "Annual", "Quarterly", or "Monthly".\n6. If the source contains multiple periods, generate a separate object in the "reports" array for EACH period.\n\nTemplate:\n{\n  "company_meta": {\n    "name": "Company Name Placeholder",\n    "stock_code": "000000",\n    "currency": "CNY"\n  },\n  "reports": [\n    {\n      "fiscal_year": "2023 Annual",\n      "period_type": "Annual",\n      "data": {\n        "income_statement": {\n          "title": "Income Statement",\n          "total_operating_revenue": {\n            "amount": 0.0,\n            "operating_revenue": 0.0,\n            "interest_income": 0.0,\n            "earned_premiums": 0.0,\n            "fee_and_commission_income": 0.0,\n            "other_business_revenue": 0.0,\n            "other_items": 0.0\n          },\n          "total_operating_cost": {\n            "amount": 0.0,\n            "operating_cost": 0.0,\n            "interest_expenses": 0.0,\n            "fee_and_commission_expenses": 0.0,\n            "taxes_and_surcharges": 0.0,\n            "selling_expenses": 0.0,\n            "admin_expenses": 0.0,\n            "rd_expenses": 0.0,\n            "financial_expenses": {\n              "amount": 0.0,\n              "interest_expenses": 0.0,\n              "interest_income": 0.0\n            },\n            "asset_impairment_loss": 0.0,\n            "credit_impairment_loss": 0.0,\n            "surrender_value": 0.0,\n            "net_compensation_expenses": 0.0,\n            "net_insurance_contract_reserves": 0.0,\n            "policy_dividend_expenses": 0.0,\n            "reinsurance_expenses": 0.0,\n            "other_business_costs": 0.0,\n            "other_items": 0.0\n          },\n          "other_operating_income": {\n            "amount": 0.0,\n            "fair_value_change_income": 0.0,\n            "investment_income": 0.0,\n            "investment_income_from_associates_jv": 0.0,\n            "net_exposure_hedging_income": 0.0,\n            "exchange_income": 0.0,\n            "asset_disposal_income": 0.0,\n            "asset_impairment_loss_new": 0.0,\n            "credit_impairment_loss_new": 0.0,\n            "other_income": 0.0,\n            "operating_profit_other_items": 0.0,\n            "operating_profit_balance_items": 0.0\n          },\n          "operating_profit": {\n            "amount": 0.0,\n            "non_operating_revenue": 0.0,\n            "non_current_asset_disposal_gain": 0.0,\n            "non_operating_expenses": 0.0,\n            "non_current_asset_disposal_loss": 0.0,\n            "other_items_affecting_total_profit": 0.0,\n            "total_profit_balance_items": 0.0\n          },\n          "total_profit": {\n            "amount": 0.0,\n            "income_tax": 0.0,\n            "unconfirmed_investment_loss": 0.0,\n            "other_items_affecting_net_profit": 0.0,\n            "net_profit_difference": 0.0\n          },\n          "net_profit": {\n            "amount": 0.0,\n            "net_profit_continuing_ops": 0.0,\n            "net_profit_discontinued_ops": 0.0,\n            "profit_from_merged_party_before_merger": 0.0,\n            "net_profit_attr_to_parent": 0.0,\n            "minority_interest_income": 0.0,\n            "net_profit_deducting_non_recurring": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0\n          },\n          "earnings_per_share": {\n            "basic_eps": 0.0,\n            "diluted_eps": 0.0\n          },\n          "other_comprehensive_income": {\n            "amount": 0.0,\n            "attr_to_parent": 0.0,\n            "attr_to_minority": 0.0\n          },\n          "total_comprehensive_income": {\n            "amount": 0.0,\n            "attr_to_parent": 0.0,\n            "attr_to_minority": 0.0,\n            "derecognition_income_amortized_cost": 0.0\n          }\n        },\n        "balance_sheet": {\n          "title": "Balance Sheet",\n          "current_assets": {\n            "monetary_funds": 0.0,\n            "clearing_settlement_funds": 0.0,\n            "lending_funds": 0.0,\n            "funds_lent": 0.0,\n            "trading_financial_assets": 0.0,\n            "financial_assets_fvpl": {\n              "amount": 0.0,\n              "trading_financial_assets": 0.0,\n              "designated_financial_assets_fvpl": 0.0\n            },\n            "derivative_financial_assets": 0.0,\n            "notes_and_accounts_receivable": {\n              "amount": 0.0,\n              "notes_receivable": 0.0,\n              "accounts_receivable": 0.0\n            },\n            "receivables_financing": 0.0,\n            "prepayments": 0.0,\n            "premiums_receivable": 0.0,\n            "reinsurance_accounts_receivable": 0.0,\n            "reinsurance_contract_reserves_receivable": 0.0,\n            "other_receivables_total": {\n              "amount": 0.0,\n              "interest_receivable": 0.0,\n              "dividends_receivable": 0.0,\n              "other_receivables": 0.0\n            },\n            "export_tax_refund_receivable": 0.0,\n            "subsidies_receivable": 0.0,\n            "internal_receivables": 0.0,\n            "buy_back_financial_assets": 0.0,\n            "financial_assets_amortized_cost": 0.0,\n            "inventories": 0.0,\n            "financial_assets_fvoci": 0.0,\n            "contract_assets": 0.0,\n            "assets_held_for_sale": 0.0,\n            "non_current_assets_due_within_1y": 0.0,\n            "agency_business_assets": 0.0,\n            "other_current_assets": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_current_assets": 0.0\n          },\n          "non_current_assets": {\n            "loans_and_advances": 0.0,\n            "debt_investments": 0.0,\n            "other_debt_investments": 0.0,\n            "financial_assets_amortized_cost_non_current": 0.0,\n            "financial_assets_fvoci_non_current": 0.0,\n            "available_for_sale_financial_assets": 0.0,\n            "held_to_maturity_investments": 0.0,\n            "long_term_receivables": 0.0,\n            "long_term_equity_investments": 0.0,\n            "investment_properties": 0.0,\n            "fixed_assets": 0.0,\n            "construction_in_progress": 0.0,\n            "construction_materials": 0.0,\n            "other_equity_instrument_investments": 0.0,\n            "other_non_current_financial_assets": 0.0,\n            "fixed_assets_liquidation": 0.0,\n            "productive_biological_assets": 0.0,\n            "oil_and_gas_assets": 0.0,\n            "right_of_use_assets": 0.0,\n            "intangible_assets": 0.0,\n            "balance_items": 0.0,\n            "development_expenses": 0.0,\n            "goodwill": 0.0,\n            "long_term_deferred_expenses": 0.0,\n            "deferred_tax_assets": 0.0,\n            "other_non_current_assets": 0.0,\n            "other_items": 0.0,\n            "total_non_current_assets": 0.0\n          },\n          "assets_summary": {\n            "other_asset_items": 0.0,\n            "asset_balance_items": 0.0,\n            "total_assets": 0.0\n          },\n          "current_liabilities": {\n            "short_term_borrowings": 0.0,\n            "borrowings_from_central_bank": 0.0,\n            "deposits_and_interbank_placements": 0.0,\n            "borrowings_from_interbank": 0.0,\n            "trading_financial_liabilities": 0.0,\n            "financial_liabilities_fvpl": {\n              "amount": 0.0,\n              "trading_financial_liabilities": 0.0,\n              "designated_financial_liabilities_fvpl": 0.0\n            },\n            "derivative_financial_liabilities": 0.0,\n            "notes_and_accounts_payable": {\n              "amount": 0.0,\n              "notes_payable": 0.0,\n              "accounts_payable": 0.0\n            },\n            "advances_from_customers": 0.0,\n            "contract_liabilities": 0.0,\n            "sell_buy_back_financial_assets": 0.0,\n            "fees_and_commissions_payable": 0.0,\n            "payroll_payable": 0.0,\n            "taxes_payable": 0.0,\n            "other_payables_total": {\n              "amount": 0.0,\n              "interest_payable": 0.0,\n              "dividends_payable": 0.0,\n              "other_payables": 0.0\n            },\n            "reinsurance_accounts_payable": 0.0,\n            "internal_payables": 0.0,\n            "estimated_current_liabilities": 0.0,\n            "insurance_contract_reserves": 0.0,\n            "acting_trading_securities": 0.0,\n            "acting_underwriting_securities": 0.0,\n            "deferred_revenue_within_1y": 0.0,\n            "financial_liabilities_amortized_cost": 0.0,\n            "short_term_bonds_payable": 0.0,\n            "liabilities_held_for_sale": 0.0,\n            "non_current_liabilities_due_within_1y": 0.0,\n            "agency_business_liabilities": 0.0,\n            "other_current_liabilities": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_current_liabilities": 0.0\n          },\n          "non_current_liabilities": {\n            "long_term_borrowings": 0.0,\n            "financial_liabilities_amortized_cost_non_current": 0.0,\n            "bonds_payable": {\n              "amount": 0.0,\n              "preference_shares": 0.0,\n              "perpetual_bonds": 0.0\n            },\n            "lease_liabilities": 0.0,\n            "long_term_payables": 0.0,\n            "long_term_payroll_payable": 0.0,\n            "special_payables": 0.0,\n            "estimated_liabilities": 0.0,\n            "deferred_revenue": 0.0,\n            "deferred_tax_liabilities": 0.0,\n            "other_non_current_liabilities": 0.0,\n            "other_items": 0.0,\n            "balance_items": 0.0,\n            "total_non_current_liabilities": 0.0\n          },\n          "liabilities_summary": {\n            "other_liability_items": 0.0,\n            "liability_balance_items": 0.0,\n            "total_liabilities": 0.0\n          },\n          "equity": {\n            "title": "Owner's Equity",\n            "paid_in_capital": 0.0,\n            "other_equity_instruments": {\n              "amount": 0.0,\n              "preference_shares": 0.0,\n              "perpetual_bonds": 0.0,\n              "other": 0.0\n            },\n            "capital_reserves": 0.0,\n            "other_comprehensive_income": 0.0,\n            "treasury_stock": 0.0,\n            "special_reserves": 0.0,\n            "surplus_reserves": 0.0,\n            "general_risk_reserves": 0.0,\n            "unconfirmed_investment_loss": 0.0,\n            "undistributed_profit": 0.0,\n            "proposed_cash_dividends": 0.0,\n            "currency_translation_diff": 0.0,\n            "parent_equity_other_items": 0.0,\n            "parent_equity_balance_items": 0.0,\n            "total_parent_equity": 0.0,\n            "minority_interests": 0.0,\n            "equity_other_items": 0.0,\n            "equity_balance_items": 0.0,\n            "total_equity": 0.0\n          },\n          "balance_check": {\n            "liabilities_and_equity_other_items": 0.0,\n            "liabilities_and_equity_balance_items": 0.0,\n            "total_liabilities_and_equity": 0.0\n          }\n        },\n        "cash_flow_statement": {\n          "title": "Cash Flow Statement",\n          "operating_activities": {\n            "cash_received_from_goods_and_services": 0.0,\n            "net_increase_deposits_interbank": 0.0,\n            "net_increase_borrowings_central_bank": 0.0,\n            "net_increase_borrowings_other_financial": 0.0,\n            "cash_received_original_premiums": 0.0,\n            "net_cash_received_reinsurance": 0.0,\n            "net_increase_insured_investment": 0.0,\n            "net_increase_disposal_trading_assets": 0.0,\n            "cash_received_interest_commission": 0.0,\n            "net_increase_borrowed_funds": 0.0,\n            "net_decrease_loans_advances": 0.0,\n            "net_increase_repurchase_funds": 0.0,\n            "tax_refunds_received": 0.0,\n            "other_cash_received_operating": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_operating": 0.0,\n            "cash_paid_for_goods_and_services": 0.0,\n            "net_increase_loans_advances": 0.0,\n            "net_increase_deposits_central_bank_interbank": 0.0,\n            "cash_paid_original_contract_claims": 0.0,\n            "cash_paid_interest_commission": 0.0,\n            "cash_paid_policy_dividends": 0.0,\n            "cash_paid_to_employees": 0.0,\n            "taxes_paid": 0.0,\n            "other_cash_paid_operating": 0.0,\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_operating": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_operating": 0.0\n          },\n          "investing_activities": {\n            "cash_received_from_investment_recovery": 0.0,\n            "cash_received_from_investment_income": 0.0,\n            "net_cash_from_disposal_assets": 0.0,\n            "net_cash_from_disposal_subsidiaries": 0.0,\n            "cash_received_from_pledge_deposit_reduction": 0.0,\n            "other_cash_received_investing": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_investing": 0.0,\n            "cash_paid_for_assets": 0.0,\n            "cash_paid_for_investments": 0.0,\n            "net_increase_pledged_loans": 0.0,\n            "net_cash_paid_subsidiaries": 0.0,\n            "cash_paid_for_pledge_deposit_increase": 0.0,\n            "other_cash_paid_investing": 0.0,\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_investing": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_investing": 0.0\n          },\n          "financing_activities": {\n            "cash_received_from_investments": {\n              "amount": 0.0,\n              "from_minority_shareholders": 0.0\n            },\n            "cash_received_from_borrowings": 0.0,\n            "cash_received_from_bond_issue": 0.0,\n            "other_cash_received_financing": 0.0,\n            "inflow_other_items": 0.0,\n            "inflow_balance_items": 0.0,\n            "subtotal_cash_inflow_financing": 0.0,\n            "cash_paid_for_debt_repayment": 0.0,\n            "cash_paid_for_dividends_and_profits": 0.0,\n            "dividends_paid_to_minority": 0.0,\n            "cash_paid_for_minority_equity": 0.0,\n            "other_cash_paid_financing": {\n              "amount": 0.0,\n              "paid_to_minority_for_capital_reduction": 0.0\n            },\n            "outflow_other_items": 0.0,\n            "outflow_balance_items": 0.0,\n            "subtotal_cash_outflow_financing": 0.0,\n            "net_cash_flow_other_items": 0.0,\n            "net_cash_flow_balance_items": 0.0,\n            "net_cash_flow_from_financing": 0.0\n          },\n          "cash_increase": {\n            "exchange_rate_effect": 0.0,\n            "increase_other_items": 0.0,\n            "increase_balance_items": 0.0,\n            "net_increase_cash_and_equivalents": 0.0,\n            "cash_at_beginning": 0.0,\n            "end_balance_other_items": 0.0,\n            "end_balance_balance_items": 0.0,\n            "cash_at_end": 0.0\n          },\n          "supplementary_info": {\n            "net_profit_adjustment": {\n              "net_profit": 0.0,\n              "asset_impairment_reserves": 0.0,\n              "depreciation_fixed_assets_investment_props": 0.0,\n              "depreciation_others": 0.0,\n              "depreciation_investment_props": 0.0,\n              "amortization_intangible_assets": 0.0,\n              "amortization_long_term_deferred": 0.0,\n              "amortization_deferred_revenue": 0.0,\n              "decrease_deferred_expenses": 0.0,\n              "increase_accrued_expenses": 0.0,\n              "loss_disposal_assets": 0.0,\n              "loss_scrapping_assets": 0.0,\n              "loss_fair_value_change": 0.0,\n              "financial_expenses": 0.0,\n              "investment_loss": 0.0,\n              "deferred_tax": 0.0,\n              "decrease_deferred_tax_assets": 0.0,\n              "increase_deferred_tax_liabilities": 0.0,\n              "increase_estimated_liabilities": 0.0,\n              "decrease_inventories": 0.0,\n              "decrease_operating_receivables": 0.0,\n              "increase_operating_payables": 0.0,\n              "other": 0.0,\n              "net_cash_flow_other_items": 0.0,\n              "net_cash_flow_balance_items": 0.0,\n              "net_cash_flow_from_operating_indirect": 0.0\n            },\n            "significant_non_cash": {\n              "debt_to_capital": 0.0,\n              "convertible_bonds_due_within_1y": 0.0,\n              "fixed_assets_finance_lease": 0.0,\n              "non_cash_items_other": 0.0\n            },\n            "cash_change_check": {\n              "cash_end_balance": 0.0,\n              "cash_begin_balance": 0.0,\n              "equivalents_end_balance": 0.0,\n              "equivalents_begin_balance": 0.0,\n              "net_increase_other": 0.0,\n              "net_increase_balance": 0.0,\n              "net_increase_cash_and_equivalents_indirect": 0.0\n            },\n            "credit_impairment_loss": 0.0\n          }\n        }\n      }\n    }\n  ]\n}`,

    // Explorer Page
    explorerTitle: "财务数据浏览",
    noDataFound: "未找到数据",
    getFinancialData: "获取财务数据",
    lineItem: "报表项目",
    type: "类型",
    incomeStatement: "利润表",
    balanceSheet: "资产负债表",
    cashFlowStatement: "现金流量表",
    showingRecords: "显示记录",
    zerosHidden: "已隐藏零值",

    // Ratios Page
    ratiosTitle: "财务比率",
    ratiosDesc: "高级财务绩效指标与比率分析。",
    comparisonMode: "比较模式",
    dupontIdentity: "杜邦分析 (ROE 分解)",
    roeFormula: "ROE = 净利率 × 资产周转率 × 权益乘数",
    returnOnEquity: "净资产收益率 (ROE)",
    ownerValueCreation: "股东价值创造",
    profitability: "盈利能力",
    efficiency: "营运效率",
    leverage: "杠杆水平",
    netMargin: "销售净利率",
    assetTurnover: "总资产周转率",
    equityMultiplier: "权益乘数",
    profitabilityMargins: "盈利能力与利润率",
    returnOnInvestment: "投资回报率",
    solvencyLiquidity: "偿债能力与流动性",
    operatingEfficiency: "营运效率",
    cashFlowQuality: "现金流质量",
    growthIndicators: "成长性指标",
    analyzing: "分析中",
    standardizedAnalysis: "标准化财务分析",

    // Charts Page
    chartsTitle: "财务图表",
    chartsDesc: "财务结构与绩效的可视化分析。",
    profitabilityTrends: "盈利趋势",
    liquidityCycle: "流动性与周期分析",
    efficiencyCost: "效率与成本结构",
    cashFlowGrowth: "现金流与增长",
    structureAnalysis: "结构分析",
    returnMetrics: "回报指标 (%)",
    revenueVsCash: "营收 vs 收现",
    netProfitVsOCF: "净利润 vs 经营现金流",
    profitSources: "利润来源构成",
    liquidityRatios: "流动性比率趋势",
    workingCapitalCycle: "营运资金周期 (天)",
    debtToAsset: "资产负债率及变动",
    turnoverRatios: "周转率指标",
    costStructure: "成本费用结构 (%)",
    cashFlowSummary: "现金流摘要",
    ocfCapexFcf: "经营现金流/资本支出/自由现金流",
    revenueGrowth: "营收增长",
    netProfitGrowth: "净利润增长",
    assetStructure: "资产结构",
    liabilityStructure: "负债结构",
    equityStructure: "权益结构",

    // Chart Data Keys
    ROE: "净资产收益率",
    "Net Margin": "净利率",
    "Gross Margin": "毛利率",
    Revenue: "营业收入",
    "Cash From Sales": "销售收现",
    "Net Profit": "净利润",
    "Operating CF": "经营现金流",
    "Main Business Profit": "主营利润",
    "Finance Expense": "财务费用",
    "Impairment Loss": "减值损失",
    "Fair Value Change": "公允价值变动",
    "Investment Income": "投资收益",
    "Asset Disposal": "资产处置",
    "Other Income": "其他收益",
    "Non-op Revenue": "营业外收入",
    "Non-op Expense": "营业外支出",
    "Current Ratio": "流动比率",
    "Quick Ratio": "速动比率",
    "Cash Ratio": "现金比率",
    DIO: "存货周转天数",
    DSO: "应收周转天数",
    DPO: "应付周转天数",
    CCC: "现金循环周期",
    "Debt Ratio": "资产负债率",
    "Debt Ratio Delta": "负债率变动",
    "Inventory Turnover": "存货周转率",
    "AR Turnover": "应收周转率",
    "Fixed Asset Turnover": "固定资产周转率",
    "Total Asset Turnover": "总资产周转率",
    COGS: "营业成本",
    "Tax & Surcharge": "税金及附加",
    "Selling Exp": "销售费用",
    "Admin Exp": "管理费用",
    "R&D Exp": "研发费用",
    "Main Profit": "主营利润",
    "Investing CF": "投资现金流",
    "Financing CF": "筹资现金流",
    Capex: "资本支出",
    "Free CF": "自由现金流",
    "Revenue Growth": "营收增长率",
    "Net Profit Growth": "净利增长率",
    "Cash & Equiv Etc": "货币资金等",
    "Receivables Etc": "应收账款等",
    Prepayments: "预付款项",
    Inventory: "存货",
    "Other Current Assets": "其他流动资产",
    "Long-term Equity Invest": "长期股权投资",
    Goodwill: "商誉",
    "Fixed Assets": "固定资产",
    "Construction In Progress": "在建工程",
    "Right-of-use Assets": "使用权资产",
    "Intangible Assets": "无形资产",
    "Other Assets": "其他资产",
    "Interest-bearing Debt": "有息负债",
    "Payables Etc": "应付账款等",
    "Prepayments Received Etc": "预收账款等",
    "Payroll Payable Etc": "应付职工薪酬",
    "Taxes Payable": "应交税费",
    "Other Payables": "其他应付款",
    "Lease Liabilities": "租赁负债",
    "Long-term Payables": "长期应付款",
    "Other Liabilities": "其他负债",
    "Paid-in Capital": "实收资本",
    "Other Equity Instruments": "其他权益工具",
    "Capital Reserves": "资本公积",
    "Other Comprehensive Income": "其他综合收益",
    "Treasury Stock": "库存股",
    "Special Reserves": "专项储备",
    "Surplus Reserves": "盈余公积",
    "Undistributed Profit": "未分配利润",
    "Minority Interests & Other": "少数股东权益",
    // Metric Descriptions
    grossMarginDesc: "毛利 / 营收",
    netProfitMarginDesc: "净利 / 营收",
    costOfSalesRatioDesc: "营业成本 / 营收",
    expenseOfSalesRatioDesc: "期间费用 / 营收",
    ebitMarginDesc: "息税前利润 / 营收",
    operatingMarginDesc: "营业利润 / 营收",
    assetImpairmentRatioDesc: "资产减值 / 营收",
    roaDesc: "总资产回报率",
    roicDesc: "投入资本回报率",
    cfroiProxyDesc: "现金流投资回报率",
    croicDesc: "现金投入资本回报率",
    currentRatioDesc: "流动资产 / 流动负债",
    quickRatioDesc: "速动资产 / 流动负债",
    cashRatioDesc: "货币资金 / 流动负债",
    debtToAssetsDesc: "总负债 / 总资产",
    debtToEquityDesc: "总负债 / 股东权益",
    interestCoverageDesc: "息税前利润 / 利息费用",
    proxyInterestRateDesc: "估算债务利息率",
    operatingCashFlowRatioDesc: "经营现金流 / 流动负债",
    nwcToAssetsDesc: "营运资金 / 总资产",
    netDebtDesc: "有息负债 - 货币资金",
    sellingExpenseRatioDesc: "销售费用 / 营收",
    adminExpenseRatioDesc: "管理费用 / 营收",
    rdExpenseRatioDesc: "研发费用 / 营收",
    inventoryTurnoverDesc: "营业成本 / 平均存货",
    daysInventoryOutstandingDesc: "存货周转天数",
    arTurnoverDesc: "营收 / 平均应收",
    daysSalesOutstandingDesc: "应收账款周转天数",
    totalAssetTurnoverDesc: "营收 / 平均总资产",
    operatingCycleDesc: "存货周转天数 + 应收周转天数",
    cashConversionCycleDesc: "营业周期 - 应付周转天数",
    workingCapitalDesc: "流动资产 - 流动负债",
    ocfToRevenueDesc: "经营现金流 / 营收",
    ocfToOperatingIncomeDesc: "经营现金流 / 营业利润",
    freeCashFlowDesc: "经营现金流 - 资本支出",
    cashCollectionRatioDesc: "销售收现 / 营收",
    ocfToDebtDesc: "经营现金流 / 总负债",
    ocfToCapexDesc: "经营现金流 / 资本支出",
    revenueGrowthDesc: "营收同比增长",
    netProfitGrowthDesc: "净利润同比增长",
    ocfGrowthDesc: "经营现金流同比增长",
    requiresPrevPeriodData: "需要上期数据",

    // Flags Page
    flagsTitle: "风险清单",
    flagsDesc: "基于财务数据的自动化取证检查。",
    riskIndicators: "风险指标",
    healthSignals: "健康信号",
    additionalData: "需补充数据",
    noFlags: "未检测到重大标记",
    noFlagsDesc: "自动化分析未发现符合标准风险或健康标准的极端异常值。",
    triggerCondition: "触发条件",
    targetCriteria: "目标标准",
    logic: "逻辑",
    risks: "风险",
    health: "健康",
    check: "检查",

    // Flag Categories
    Liquidity: "流动性",
    Revenue: "营收",
    Cost: "成本",
    Asset: "资产",
    Debt: "债务",
    Earnings: "盈利",
    Growth: "增长",

    // Flag Names
    "Abnormal Gross Margin Expansion": "毛利率异常扩张",
    "Inventory Divergence": "存货与营收背离",
    "High Cash Interest Rate": "高额现金利息率",
    "Inverted Interest Rate": "利息收入收益率倒挂",
    "High-Cash, High-Debt": "存贷双高",
    "Asset Disposal Reliance": "依赖资产处置收益",
    "Asset Impairment Surge": "资产减值激增",
    "Credit Impairment Surge": "信用减值激增",
    "Non-Operating Rev Dependency": "依赖营业外收入",
    "Fair Value Reliance": "依赖公允价值变动",
    "Investment Income Reliance": "依赖投资收益",
    "Other Income Reliance": "依赖其他收益",
    "Accounts Receivable Bloat": "应收账款膨胀",
    "Excessive Inventory": "存货积压",
    "Other Receivables Anomaly": "其他应收款异常",
    "Goodwill Risk": "商誉风险",
    "CIP Trap": "在建工程陷阱",
    "Deferred Expense Bloat": "长期待摊费用膨胀",
    "Other Payables Anomaly": "其他应付款异常",
    "Selling Expense Efficiency": "销售费用效率低下",
    "Admin Expense Divergence": "管理费用背离",
    "Prepayment Surge": "预付款项激增",
    "Payables Gap": "应付账款缺口",
    "Other Cash Received Anomaly": "收到其他经营现金异常",
    "Cash-Backed Profits": "盈利现金保障倍数高",
    "Self-Funding": "具备造血能力",
    "Conservative Leverage": "杠杆稳健",
    "Cash-Profit Divergence": "净利与现金流背离",
    "Low OCF/NI Ratio": "净现比过低",
    "Rising DSO": "应收周转天数大幅上升",
    "High Total Accruals": "应计项目占比过高",
    "Debt Cliff": "短债长投风险",
    "Margin Divergence": "毛利率与净利率背离",
    "Negative FCF": "自由现金流持续为负",
    "Payables Stretch": "拖欠供应商款项",

    // Flag Descriptions
    "Rising margins with slowing inventory turnover suggests potential earnings inflation via capitalization or failure to write down obsolete goods.":
      "毛利率上升但存货周转放缓，暗示可能通过资本化虚增利润或未计提存货跌价。",
    "Inventory growing significantly faster than sales suggests falling demand, obsolescence, or channel stuffing.":
      "存货增长显著快于营收，暗示需求下降、产品滞销或渠道塞货。",
    "Paying an excessively high rate on debt (or dividends included) can signal high-risk borrowing status.":
      "支付过高的债务利息（或包含股利）可能暗示高风险借贷状态。",
    "Extremely low yield on cash balances suggests funds may be restricted, pledged, or non-existent.":
      "货币资金收益率极低，暗示资金可能受限、被质押或虚构。",
    "Coexistence of high cash coverage and high debt/leverage, often indicating restricted or fictitious cash.":
      "高现金与高债务并存，通常暗示资金受限或虚假。",
    "Relying on selling assets to generate profit is unsustainable and masks core business weakness.":
      "依赖出售资产获利不可持续，且掩盖了核心业务的疲软。",
    "Large write-downs ('Big Bath') indicate inflated past earnings or clearing decks for future.":
      "巨额资产减值（“洗大澡”）暗示过去利润虚增或为未来业绩腾挪空间。",
    "Sharp deterioration in receivables quality, suggesting customer defaults.":
      "应收账款质量急剧恶化，暗示客户违约风险。",
    "Earnings driven by grants/fines rather than operations are low quality.":
      "主要靠补助或罚款获利，盈利质量低。",
    "Profits driven by paper gains are risky and don't reflect cash generation.":
      "利润主要来自账面浮盈，风险高且无现金流支持。",
    "Reliance on trading stocks or subsidiaries rather than main product.":
      "依赖炒股或子公司投资收益，而非主营业务。",
    "Profit derived from 'Other Income' is often non-persistent.":
      "利润来自“其他收益”，通常不可持续。",
    "Receivables growing faster than sales signals channel stuffing or relaxed credit terms.":
      "应收账款增长快于营收，暗示渠道塞货或放宽信用政策。",
    "Inventory growing faster than sales often signals potential write-downs.":
      "存货增长快于营收，通常暗示潜在的减值风险。",
    "Hiding place for misappropriated funds or loans to shareholders.":
      "可能隐藏被挪用的资金或对股东的借款。",
    "High goodwill suggests aggressive acquisitions; risk of massive write-offs.":
      "高商誉暗示激进并购，存在巨额减值风险。",
    "CIP that doesn't convert to fixed assets may be capitalized expense or fraud.":
      "迟迟不转固的在建工程，可能是资本化的费用或造假。",
    "Used to hide current expenses to artificially boost profits.":
      "用于隐藏当期费用以人为推高利润。",
    "Can hide off-book loans or illicit financing.":
      "可能隐藏表外借款或非法融资。",
    "Revenue skyrocketing while marketing costs stay flat is highly suspicious.":
      "营收飙升但营销费用持平，非常可疑。",
    "Admin costs growing much faster than sales indicates inefficiency or unchecked compensation.":
      "管理费用增长远快于营收，显示效率低下或薪酬失控。",
    "Massive prepayments are common vehicles for embezzlement or fund transfer.":
      "巨额预付款常是挪用资金或利益输送的工具。",
    "Excessive payables growth signals liquidity stress—suppliers are funding the company.":
      "应付账款过度增长暗示流动性压力——靠供应商输血。",
    "Often used to hide non-operating cash to inflate OCF.":
      "常用于隐藏非经营性现金以虚增经营现金流。",
    "Operating Cash Flow exceeds Total Net Profit, indicating high quality of earnings for the consolidated group.":
      "经营现金流超过净利润，显示集团盈利质量高。",
    "The company generates enough cash to fully fund its capital expenditures and growth.":
      "公司产生的现金足以完全覆盖资本支出和增长需求。",
    "Debt levels are low relative to earnings, indicating a strong balance sheet.":
      "相对于盈利，债务水平较低，资产负债表强劲。",
    "Total profits are growing rapidly while cash flow is stagnant or falling, indicating low quality earnings.":
      "利润快速增长但现金流停滞或下降，暗示盈利质量低。",
    "Operating cash flow is significantly lower than reported total net income.":
      "经营现金流显著低于报告的净利润。",
    "It is taking significantly longer to collect payment from customers.":
      "回款周期显著变长。",
    "Earnings are driven heavily by non-cash accruals rather than cash flow.":
      "盈利主要由非现金应计项目驱动，而非现金流。",
    "Reliance on short-term debt exposes the company to refinancing risks.":
      "依赖短期债务面临再融资风险。",
    "Gross margin improved but Operating margin declined, suggesting rising overheads or expense reclassification.":
      "毛利率改善但营业利润率下降，暗示费用上升或费用重分类。",
    "Free Cash Flow has been negative for consecutive periods despite any reported profits.":
      "尽管报告盈利，但自由现金流连续多期为负。",
    "Days Payable Outstanding increased significantly, potentially delaying payments to suppliers to boost cash.":
      "应付周转天数显著增加，可能通过拖欠供应商来增加现金。",

    // Insights Page
    aiInsightsTitle: "AI 洞察",
    aiInsightsDesc: "关键财务比率与异常的 AI 辅助分析。",
    aiModel: "AI 模型",
    dataContext: "数据上下文",
    generateInsights: "生成洞察",
    analyzingSpinner: "分析中...",
    synthesizing: "正在合成财务叙事...",
    connectingTo: "正在连接模型...",
    noAnalysis: "尚未生成分析",
    clickToGenerate: "点击“生成洞察”开始分析。",
    downloadMD: "下载 Markdown",
    modelGemini: "Google Gemini (均衡)",
    modelDeepseek: "DeepSeek R1 (深度取证)",
    modelQwen: "Alibaba Qwen (中文语境)",

    // Report Page
    reportTitle: "报告生成器",
    exportSettings: "导出设置",
    format: "格式",
    includeSections: "包含章节",
    downloadPDF: "下载 PDF",
    downloadMarkdown: "下载 Markdown",
    companySummary: "公司摘要",
    financialMetrics: "财务指标",
    chartsVisuals: "图表与可视化",
    signalAnalysis: "信号分析",
    rawDataAppendix: "原始数据附录",
    generatedOn: "生成于",
    generatedVia: "生成模型：",
    executiveSummary: "执行摘要",
    mockReportTitle: "财务分析报告",
    mockExecSummaryText:
      "公司营收保持稳健，稳定在 23.9 亿元。然而，盈利信号表明需要密切关注运营支出。营运资金效率仍然是一个关键优势。",
    mockSignalTriggered: "由于现金余额高（12亿元）且短期债务负担重而触发。",

    // Generated from backend/app/core/mappings.py
    "Accounts Payable": "应付账款",
    "Accounts Receivable": "应收账款",
    "Acting Trading Securities": "代理买卖证券款",
    "Acting Underwriting Securities": "代理承销证券款",
    "Admin Expenses": "管理费用",
    "Advances From Customers": "预收款项",
    "Agency Business Assets": "代理业务资产",
    "Agency Business Liabilities": "代理业务负债",
    "Amortization Deferred Revenue": "递延收益摊销",
    "Amortization Intangible Assets": "无形资产摊销",
    "Amortization Long Term Deferred": "长期待摊费用摊销",
    "Asset Balance Items": "资产平衡项目",
    "Asset Disposal Income": "资产处置收益",
    "Asset Impairment Loss": "资产减值损失",
    "Asset Impairment Loss New": "资产减值损失(新)",
    "Asset Impairment Reserves": "资产减值准备",
    "Assets Held For Sale": "划分为持有待售的资产",
    "Attr To Minority": "归属于少数股东的其他综合收益的税后净额",
    "Attr To Parent": "归属于母公司所有者的其他综合收益的税后净额",
    "Available For Sale Financial Assets": "可供出售金融资产",
    "Balance Items": "净利润差额(合计平衡项目)",
    "Basic Eps": "基本每股收益",
    "Bonds Payable": "应付债券",
    "Borrowings From Central Bank": "向中央银行借款",
    "Borrowings From Interbank": "拆入资金",
    "Buy Back Financial Assets": "买入返售金融资产",
    "Capital Reserves": "资本公积",
    "Cash At Beginning": "期初现金及现金等价物余额",
    "Cash At End": "期末现金及现金等价物余额",
    "Cash Begin Balance": "现金的期初余额",
    "Cash End Balance": "现金的期末余额",
    "Cash Paid For Assets": "购建固定资产、无形资产和其他长期资产支付的现金",
    "Cash Paid For Debt Repayment": "偿还债务支付的现金",
    "Cash Paid For Dividends And Profits": "分配股利、利润或偿付利息支付的现金",
    "Cash Paid For Goods And Services": "购买商品、接受劳务支付的现金",
    "Cash Paid For Investments": "投资支付的现金",
    "Cash Paid For Minority Equity": "购买子公司少数股权而支付的现金",
    "Cash Paid For Pledge Deposit Increase": "增加质押和定期存款所支付的现金",
    "Cash Paid Interest Commission": "支付利息、手续费及佣金的现金",
    "Cash Paid Original Contract Claims": "支付原保险合同赔付款项的现金",
    "Cash Paid Policy Dividends": "支付保单红利的现金",
    "Cash Paid To Employees": "支付给职工以及为职工支付的现金",
    "Cash Received From Bond Issue": "发行债券收到的现金",
    "Cash Received From Borrowings": "取得借款收到的现金",
    "Cash Received From Goods And Services": "销售商品、提供劳务收到的现金",
    "Cash Received From Investment Income": "取得投资收益收到的现金",
    "Cash Received From Investment Recovery": "收回投资收到的现金",
    "Cash Received From Investments": "吸收投资收到的现金",
    "Cash Received From Pledge Deposit Reduction":
      "减少质押和定期存款所收到的现金",
    "Cash Received Interest Commission": "收取利息、手续费及佣金的现金",
    "Cash Received Original Premiums": "收到原保险合同保费取得的现金",
    "Clearing Settlement Funds": "结算备付金",
    "Construction In Progress": "在建工程",
    "Construction Materials": "工程物资",
    "Contract Assets": "合同资产",
    "Contract Liabilities": "合同负债",
    "Convertible Bonds Due Within 1y": "一年内到期的可转换公司债券",
    "Credit Impairment Loss": "信用减值损失",
    "Credit Impairment Loss New": "信用减值损失(新)",
    "Currency Translation Diff": "外币报表折算差额",
    "Debt Investments": "债权投资",
    "Debt To Capital": "债务转为资本",
    "Decrease Deferred Expenses": "待摊费用的减少",
    "Decrease Deferred Tax Assets": "递延所得税资产减少",
    "Decrease Inventories": "存货的减少",
    "Decrease Operating Receivables": "经营性应收项目的减少",
    "Deferred Revenue": "递延收益",
    "Deferred Revenue Within 1y": "一年内的递延收益",
    "Deferred Tax": "递延所得税",
    "Deferred Tax Assets": "递延所得税资产",
    "Deferred Tax Liabilities": "递延所得税负债",
    "Deposits And Interbank Placements": "吸收存款及同业存放",
    "Depreciation Fixed Assets Investment Props": "固定资产和投资性房地产折旧",
    "Depreciation Investment Props": "投资性房地产折旧摊销",
    "Depreciation Others": "其中:固定资产折旧",
    "Derecognition Income Amortized Cost":
      "以摊余成本计量的金融资产终止确认收益",
    "Derivative Financial Assets": "衍生金融资产",
    "Derivative Financial Liabilities": "衍生金融负债",
    "Designated Financial Assets Fvpl":
      "其中:指定以公允价值计量且其变动计入当期损益的金融资产",
    "Designated Financial Liabilities Fvpl":
      "其中:指定以公允价值计量且其变动计入当期损益的金融负债",
    "Development Expenses": "开发支出",
    "Diluted Eps": "稀释每股收益",
    "Dividends Paid To Minority": "其中:子公司支付给少数股东的股利、利润",
    "Dividends Payable": "应付股利",
    "Dividends Receivable": "应收股利",
    "Earned Premiums": "已赚保费",
    "End Balance Balance Items": "期末现金及现金等价物余额平衡项目",
    "End Balance Other Items": "期末现金及现金等价物余额其他项目",
    "Equity Balance Items": "股权权益平衡项目",
    "Equity Other Items": "股东权益其他项目",
    "Equivalents Begin Balance": "现金等价物的期初余额",
    "Equivalents End Balance": "现金等价物的期末余额",
    "Estimated Current Liabilities": "预计流动负债",
    "Estimated Liabilities": "预计负债",
    "Exchange Income": "汇兑收益",
    "Exchange Rate Effect": "汇率变动对现金及现金等价物的影响",
    "Export Tax Refund Receivable": "应收出口退税",
    "Fair Value Change Income": "公允价值变动收益",
    "Fee And Commission Expenses": "手续费及佣金支出",
    "Fee And Commission Income": "手续费及佣金收入",
    "Fees And Commissions Payable": "应付手续费及佣金",
    "Financial Assets Amortized Cost": "以摊余成本计量的金融资产",
    "Financial Assets Amortized Cost Non Current":
      "以摊余成本计量的金融资产(非流动)",
    "Financial Assets Fvoci":
      "以公允价值计量且其变动计入其他综合收益的金融资产",
    "Financial Assets Fvoci Non Current":
      "以公允价值计量且其变动计入其他综合收益的金融资产(非流动)",
    "Financial Assets Fvpl": "以公允价值计量且其变动计入当期损益的金融资产",
    "Financial Expenses": "财务费用",
    "Financial Liabilities Amortized Cost": "以摊余成本计量的金融负债",
    "Financial Liabilities Amortized Cost Non Current":
      "以摊余成本计量的金融负债(非流动)",
    "Financial Liabilities Fvpl":
      "以公允价值计量且其变动计入当期损益的金融负债",
    "Fixed Assets": "固定资产",
    "Fixed Assets Finance Lease": "融资租入固定资产",
    "Fixed Assets Liquidation": "固定资产清理",
    "From Minority Shareholders": "其中:子公司吸收少数股东投资收到的现金",
    "Funds Lent": "拆出资金",
    "General Risk Reserves": "一般风险准备",
    Goodwill: "商誉",
    "Held To Maturity Investments": "持有至到期投资",
    "Income Tax": "减:所得税费用",
    "Increase Accrued Expenses": "预提费用的增加",
    "Increase Balance Items": "现金及现金等价物净增加额平衡项目",
    "Increase Deferred Tax Liabilities": "递延所得税负债增加",
    "Increase Estimated Liabilities": "预计负债的增加",
    "Increase Operating Payables": "经营性应付项目的增加",
    "Increase Other Items": "现金及现金等价物净增加额其他项目",
    "Inflow Balance Items": "经营活动现金流入平衡项目",
    "Inflow Other Items": "经营活动现金流入其他项目",
    "Insurance Contract Reserves": "保险合同准备金",
    "Intangible Assets": "无形资产",
    "Interest Expenses": "利息支出",
    "Interest Income": "利息收入",
    "Interest Payable": "应付利息",
    "Interest Receivable": "应收利息",
    "Internal Payables": "内部应付款",
    "Internal Receivables": "内部应收款",
    Inventories: "存货",
    "Investment Income": "投资收益",
    "Investment Income From Associates Jv":
      "其中:对联营企业和合营企业的投资收益",
    "Investment Loss": "投资损失",
    "Investment Properties": "投资性房地产",
    "Lease Liabilities": "租赁负债",
    "Lending Funds": "融出资金",
    "Liabilities And Equity Balance Items": "负债及股东权益平衡项目",
    "Liabilities And Equity Other Items": "负债和股东权益其他项目",
    "Liabilities Held For Sale": "划分为持有待售的负债",
    "Liability Balance Items": "负债平衡项目",
    "Loans And Advances": "发放贷款及垫款",
    "Long Term Borrowings": "长期借款",
    "Long Term Deferred Expenses": "长期待摊费用",
    "Long Term Equity Investments": "长期股权投资",
    "Long Term Payables": "长期应付款",
    "Long Term Payroll Payable": "长期应付职工薪酬",
    "Long Term Receivables": "长期应收款",
    "Loss Disposal Assets": "处置固定资产、无形资产和其他长期资产的损失",
    "Loss Fair Value Change": "公允价值变动损失",
    "Loss Scrapping Assets": "固定资产报废损失",
    "Minority Interest Income": "少数股东损益",
    "Minority Interests": "少数股东权益",
    "Monetary Funds": "货币资金",
    "Net Cash Flow Balance Items": "经营活动现金流量净额平衡项目",
    "Net Cash Flow From Financing": "筹资活动产生的现金流量净额",
    "Net Cash Flow From Investing": "投资活动产生的现金流量净额",
    "Net Cash Flow From Operating": "经营活动产生的现金流量净额",
    "Net Cash Flow From Operating Indirect": "经营活动现金流量净额(补充)",
    "Net Cash Flow Other Items": "经营活动产生的现金流量净额其他项目",
    "Net Cash From Disposal Assets":
      "处置固定资产、无形资产和其他长期资产收回的现金净额",
    "Net Cash From Disposal Subsidiaries":
      "处置子公司及其他营业单位收到的现金净额",
    "Net Cash Paid Subsidiaries": "取得子公司及其他营业单位支付的现金净额",
    "Net Cash Received Reinsurance": "收到再保险业务现金净额",
    "Net Compensation Expenses": "赔付支出净额",
    "Net Decrease Loans Advances": "发放贷款及垫款的净减少额",
    "Net Exposure Hedging Income": "净敞口套期收益",
    "Net Increase Balance": "现金及现金等价物净增加额平衡项目",
    "Net Increase Borrowed Funds": "拆入资金净增加额",
    "Net Increase Borrowings Central Bank": "向中央银行借款净增加额",
    "Net Increase Borrowings Other Financial": "向其他金融机构拆入资金净增加额",
    "Net Increase Cash And Equivalents": "现金及现金等价物净增加额",
    "Net Increase Cash And Equivalents Indirect":
      "现金及现金等价物净增加额(补充)",
    "Net Increase Deposits Central Bank Interbank":
      "存放中央银行和同业款项净增加额",
    "Net Increase Deposits Interbank": "客户存款和同业存放款项净增加额",
    "Net Increase Disposal Trading Assets": "处置交易性金融资产净增加额",
    "Net Increase Insured Investment": "保户储金及投资款净增加额",
    "Net Increase Loans Advances": "客户贷款及垫款净增加额",
    "Net Increase Other": "现金及现金等价物净增加额其他项目",
    "Net Increase Pledged Loans": "质押贷款净增加额",
    "Net Increase Repurchase Funds": "回购业务资金净增加额",
    "Net Insurance Contract Reserves": "提取保险合同准备金净额",
    "Net Profit": "净利润",
    "Net Profit Attr To Parent": "归属于母公司所有者的净利润",
    "Net Profit Continuing Ops": "持续经营净利润",
    "Net Profit Deducting Non Recurring": "扣除非经常性损益后的净利润",
    "Net Profit Difference": "净利润差额(合计平衡项目2)",
    "Net Profit Discontinued Ops": "终止经营净利润",
    "Non Cash Items Other": "不涉及现金收支的投资和筹资活动金额其他项目",
    "Non Current Asset Disposal Gain": "非流动资产处置利得",
    "Non Current Asset Disposal Loss": "非流动资产处置净损失",
    "Non Current Assets Due Within 1y": "一年内到期的非流动资产",
    "Non Current Liabilities Due Within 1y": "一年内到期的非流动负债",
    "Non Operating Expenses": "减:营业外支出",
    "Non Operating Revenue": "加:营业外收入",
    "Notes And Accounts Payable": "应付票据及应付账款",
    "Notes And Accounts Receivable": "应收票据及应收账款",
    "Notes Payable": "应付票据",
    "Notes Receivable": "应收票据",
    "Oil And Gas Assets": "油气资产",
    "Operating Cost": "营业成本",
    "Operating Profit": "营业利润",
    "Operating Profit Balance Items": "营业利润平衡项目",
    "Operating Profit Other Items": "营业利润其他项目",
    "Operating Revenue": "营业收入",
    Other: "其他",
    "Other Asset Items": "资产其他项目",
    "Other Business Costs": "其他业务成本",
    "Other Business Revenue": "其他业务收入",
    "Other Cash Paid Financing": "支付其他与筹资活动有关的现金",
    "Other Cash Paid Investing": "支付其他与投资活动有关的现金",
    "Other Cash Paid Operating": "支付其他与经营活动有关的现金",
    "Other Cash Received Financing": "收到其他与筹资活动有关的现金",
    "Other Cash Received Investing": "收到其他与投资活动有关的现金",
    "Other Cash Received Operating": "收到其他与经营活动有关的现金",
    "Other Comprehensive Income": "其他综合收益",
    "Other Current Assets": "其他流动资产",
    "Other Current Liabilities": "其他流动负债",
    "Other Debt Investments": "其他债权投资",
    "Other Equity Instrument Investments": "其他权益工具投资",
    "Other Equity Instruments": "其他权益工具",
    "Other Income": "加:其他收益",
    "Other Items": "营业总收入其他项目",
    "Other Items Affecting Net Profit": "影响净利润的其他项目",
    "Other Items Affecting Total Profit": "影响利润总额的其他项目",
    "Other Liability Items": "负债其他项目",
    "Other Non Current Assets": "其他非流动资产",
    "Other Non Current Financial Assets": "其他非流动金融资产",
    "Other Non Current Liabilities": "其他非流动负债",
    "Other Operating Income": "其他经营收益",
    "Other Payables": "其中:其他应付款",
    "Other Payables Total": "其他应付款",
    "Other Receivables": "其中:其他应收款",
    "Other Receivables Total": "其他应收款",
    "Outflow Balance Items": "经营活动现金流出平衡项目",
    "Outflow Other Items": "经营活动现金流出其他项目",
    "Paid In Capital": "实收资本(或股本)",
    "Paid To Minority For Capital Reduction":
      "其中：子公司减资支付给少数股东的现金",
    "Parent Equity Balance Items": "归属于母公司股东权益平衡项目",
    "Parent Equity Other Items": "归属于母公司股东权益其他项目",
    "Payroll Payable": "应付职工薪酬",
    "Perpetual Bonds": "其中:永续债(应付债券)",
    "Policy Dividend Expenses": "保单红利支出",
    "Preference Shares": "其中:优先股(应付债券)",
    "Premiums Receivable": "应收保费",
    Prepayments: "预付款项",
    "Productive Biological Assets": "生产性生物资产",
    "Profit From Merged Party Before Merger": "被合并方在合并前实现利润",
    "Proposed Cash Dividends": "拟分配现金股利",
    "Rd Expenses": "研发费用",
    "Receivables Financing": "应收款项融资",
    "Reinsurance Accounts Payable": "应付分保账款",
    "Reinsurance Accounts Receivable": "应收分保账款",
    "Reinsurance Contract Reserves Receivable": "应收分保合同准备金",
    "Reinsurance Expenses": "分保费用",
    "Right Of Use Assets": "使用权资产",
    "Sell Buy Back Financial Assets": "卖出回购金融资产款",
    "Selling Expenses": "销售费用",
    "Short Term Bonds Payable": "应付短期债券",
    "Short Term Borrowings": "短期借款",
    "Special Payables": "专项应付款",
    "Special Reserves": "专项储备",
    "Subsidies Receivable": "应收补贴款",
    "Subtotal Cash Inflow Financing": "筹资活动现金流入小计",
    "Subtotal Cash Inflow Investing": "投资活动现金流入小计",
    "Subtotal Cash Inflow Operating": "经营活动现金流入小计",
    "Subtotal Cash Outflow Financing": "筹资活动现金流出小计",
    "Subtotal Cash Outflow Investing": "投资活动现金流出小计",
    "Subtotal Cash Outflow Operating": "经营活动现金流出小计",
    "Surplus Reserves": "盈余公积",
    "Surrender Value": "退保金",
    "Tax Refunds Received": "收到的税费返还",
    "Taxes And Surcharges": "营业税金及附加",
    "Taxes Paid": "支付的各项税费",
    "Taxes Payable": "应交税费",
    "Total Assets": "资产总计",
    "Total Comprehensive Income": "综合收益总额",
    "Total Current Assets": "流动资产合计",
    "Total Current Liabilities": "流动负债合计",
    "Total Equity": "所有者权益合计",
    "Total Liabilities": "负债合计",
    "Total Liabilities And Equity": "负债和所有者权益总计",
    "Total Non Current Assets": "非流动资产合计",
    "Total Non Current Liabilities": "非流动负债合计",
    "Total Operating Cost": "营业总成本",
    "Total Operating Revenue": "营业总收入",
    "Total Parent Equity": "归属于母公司所有者权益合计",
    "Total Profit": "利润总额",
    "Total Profit Balance Items": "利润总额平衡项目",
    "Trading Financial Assets": "交易性金融资产",
    "Trading Financial Liabilities": "交易性金融负债",
    "Treasury Stock": "减:库存股",
    "Unconfirmed Investment Loss": "未确认投资损失",
    "Undistributed Profit": "未分配利润",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  // Load language from local storage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem(
      "insight_viewer_language"
    ) as Language;
    if (savedLang && (savedLang === "en" || savedLang === "zh")) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("insight_viewer_language", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: handleSetLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
