# Mapping Chinese Excel Terms to Pydantic Schema Paths (Dot Notation)

# Note: The keys are the Chinese terms found in standard reports.
# The values are the path in the JSON/Pydantic structure: "parent_field.child_field"
# If a field is a top-level total within a group (L1), it often maps to "group_name.amount"

INCOME_STATEMENT_MAP = {
    # L1: 营业总收入
    "一、营业总收入": "total_operating_revenue.amount",
    "营业总收入": "total_operating_revenue.amount",
    "营业收入": "total_operating_revenue.operating_revenue",
    "利息收入": "total_operating_revenue.interest_income",
    "已赚保费": "total_operating_revenue.earned_premiums",
    "手续费及佣金收入": "total_operating_revenue.fee_and_commission_income",
    "其他业务收入": "total_operating_revenue.other_business_revenue",
    "营业总收入其他项目": "total_operating_revenue.other_items",
    
    # L1: 营业总成本
    "二、营业总成本": "total_operating_cost.amount",
    "营业总成本": "total_operating_cost.amount",
    "营业成本": "total_operating_cost.operating_cost",
    "利息支出": "total_operating_cost.interest_expenses",
    "手续费及佣金支出": "total_operating_cost.fee_and_commission_expenses",
    "营业税金及附加": "total_operating_cost.taxes_and_surcharges",
    "税金及附加": "total_operating_cost.taxes_and_surcharges",
    "销售费用": "total_operating_cost.selling_expenses",
    "管理费用": "total_operating_cost.admin_expenses",
    "研发费用": "total_operating_cost.rd_expenses",
    "财务费用": "total_operating_cost.financial_expenses.amount",
    "其中:利息费用": "total_operating_cost.financial_expenses.interest_expenses",
    "其中:利息收入": "total_operating_cost.financial_expenses.interest_income",
    "资产减值损失": "total_operating_cost.asset_impairment_loss",
    "信用减值损失": "total_operating_cost.credit_impairment_loss",
    "退保金": "total_operating_cost.surrender_value",
    "赔付支出净额": "total_operating_cost.net_compensation_expenses",
    "提取保险合同准备金净额": "total_operating_cost.net_insurance_contract_reserves",
    "保单红利支出": "total_operating_cost.policy_dividend_expenses",
    "分保费用": "total_operating_cost.reinsurance_expenses",
    "其他业务成本": "total_operating_cost.other_business_costs",
    "营业总成本其他项目": "total_operating_cost.other_items",
    
    # L1: 其他经营收益
    "加:其他收益": "other_operating_income.other_income",
    "其他收益": "other_operating_income.other_income",
    "投资收益": "other_operating_income.investment_income",
    "其中:对联营企业和合营企业的投资收益": "other_operating_income.investment_income_from_associates_jv",
    "公允价值变动收益": "other_operating_income.fair_value_change_income",
    "汇兑收益": "other_operating_income.exchange_income",
    "资产处置收益": "other_operating_income.asset_disposal_income",
    "净敞口套期收益": "other_operating_income.net_exposure_hedging_income",
    "资产减值损失(新)": "other_operating_income.asset_impairment_loss_new",
    "信用减值损失(新)": "other_operating_income.credit_impairment_loss_new",
    "营业利润其他项目": "other_operating_income.operating_profit_other_items",
    "营业利润平衡项目": "other_operating_income.operating_profit_balance_items",
    
    # L1: 营业利润
    "三、营业利润": "operating_profit.amount",
    "营业利润": "operating_profit.amount",
    "加:营业外收入": "operating_profit.non_operating_revenue",
    "营业外收入": "operating_profit.non_operating_revenue",
    "减:营业外支出": "operating_profit.non_operating_expenses",
    "营业外支出": "operating_profit.non_operating_expenses",
    "非流动资产处置利得": "operating_profit.non_current_asset_disposal_gain",
    "非流动资产处置净损失": "operating_profit.non_current_asset_disposal_loss",
    "影响利润总额的其他项目": "operating_profit.other_items_affecting_total_profit",
    "利润总额平衡项目": "operating_profit.total_profit_balance_items",
    
    # L1: 利润总额
    "四、利润总额": "total_profit.amount",
    "利润总额": "total_profit.amount",
    "减:所得税费用": "total_profit.income_tax",
    "所得税费用": "total_profit.income_tax",
    "所得税": "total_profit.income_tax",
    "减:所得税": "total_profit.income_tax",
    "未确认投资损失": "total_profit.unconfirmed_investment_loss",
    "影响净利润的其他项目": "total_profit.other_items_affecting_net_profit",
    "净利润差额(合计平衡项目2)": "total_profit.net_profit_difference",
    
    # L1: 净利润
    "五、净利润": "net_profit.amount",
    "净利润": "net_profit.amount",
    "持续经营净利润": "net_profit.net_profit_continuing_ops",
    "终止经营净利润": "net_profit.net_profit_discontinued_ops",
    "归属于母公司所有者的净利润": "net_profit.net_profit_attr_to_parent",
    "归属于母公司股东的净利润": "net_profit.net_profit_attr_to_parent",
    "少数股东损益": "net_profit.minority_interest_income",
    "被合并方在合并前实现利润": "net_profit.profit_from_merged_party_before_merger",
    "扣除非经常性损益后的净利润": "net_profit.net_profit_deducting_non_recurring",
    "净利润其他项目": "net_profit.other_items",
    "净利润差额(合计平衡项目)": "net_profit.balance_items",
    
    # L1: EPS
    "基本每股收益": "earnings_per_share.basic_eps",
    "稀释每股收益": "earnings_per_share.diluted_eps",
    
    # L1: Other Comprehensive Income
    "六、其他综合收益的税后净额": "other_comprehensive_income.amount",
    "其他综合收益": "other_comprehensive_income.amount",
    "归属于母公司所有者的其他综合收益的税后净额": "other_comprehensive_income.attr_to_parent",
    "归属于少数股东的其他综合收益的税后净额": "other_comprehensive_income.attr_to_minority",
    
    # L1: Total Comprehensive Income
    "七、综合收益总额": "total_comprehensive_income.amount",
    "综合收益总额": "total_comprehensive_income.amount",
    "归属于母公司所有者的综合收益总额": "total_comprehensive_income.attr_to_parent",
    "归属于母公司普通股股东综合收益总额": "total_comprehensive_income.attr_to_parent",
    "归属于少数股东的综合收益总额": "total_comprehensive_income.attr_to_minority",
    "以摊余成本计量的金融资产终止确认收益": "total_comprehensive_income.derecognition_income_amortized_cost",
}

BALANCE_SHEET_MAP = {
    # Assets - Current
    "流动资产": "current_assets.total_current_assets", # Context dependent, sometimes header
    "流动资产合计": "current_assets.total_current_assets",
    "货币资金": "current_assets.monetary_funds",
    "结算备付金": "current_assets.clearing_settlement_funds",
    "融出资金": "current_assets.lending_funds",
    "拆出资金": "current_assets.funds_lent",
    "交易性金融资产": "current_assets.financial_assets_fvpl.trading_financial_assets", # Mapping to subset for simplicity or direct
    "其中:交易性金融资产": "current_assets.financial_assets_fvpl.trading_financial_assets",
    "其中:指定以公允价值计量且其变动计入当期损益的金融资产": "current_assets.financial_assets_fvpl.designated_financial_assets_fvpl",
    "衍生金融资产": "current_assets.derivative_financial_assets",
    "应收票据": "current_assets.notes_and_accounts_receivable.notes_receivable",
    "应收账款": "current_assets.notes_and_accounts_receivable.accounts_receivable",
    "应收票据及应收账款": "current_assets.notes_and_accounts_receivable.amount",
    "应收款项融资": "current_assets.receivables_financing",
    "预付款项": "current_assets.prepayments",
    "应收保费": "current_assets.premiums_receivable",
    "应收分保账款": "current_assets.reinsurance_accounts_receivable",
    "应收分保合同准备金": "current_assets.reinsurance_contract_reserves_receivable",
    "应收利息": "current_assets.other_receivables_total.interest_receivable",
    "其中:应收利息": "current_assets.other_receivables_total.interest_receivable",
    "应收股利": "current_assets.other_receivables_total.dividends_receivable",
    "其中:应收股利": "current_assets.other_receivables_total.dividends_receivable",
    "其他应收款": "current_assets.other_receivables_total.amount",
    "其中:其他应收款": "current_assets.other_receivables_total.other_receivables",
    "其他应收款合计": "current_assets.other_receivables_total.amount",
    "应收出口退税": "current_assets.export_tax_refund_receivable",
    "应收补贴款": "current_assets.subsidies_receivable",
    "内部应收款": "current_assets.internal_receivables",
    "买入返售金融资产": "current_assets.buy_back_financial_assets",
    "以摊余成本计量的金融资产": "current_assets.financial_assets_amortized_cost",
    "存货": "current_assets.inventories",
    "以公允价值计量且其变动计入其他综合收益的金融资产": "current_assets.financial_assets_fvoci",
    "合同资产": "current_assets.contract_assets",
    "划分为持有待售的资产": "current_assets.assets_held_for_sale",
    "持有待售资产": "current_assets.assets_held_for_sale",
    "一年内到期的非流动资产": "current_assets.non_current_assets_due_within_1y",
    "代理业务资产": "current_assets.agency_business_assets",
    "其他流动资产": "current_assets.other_current_assets",
    "流动资产其他项目": "current_assets.other_items",
    "流动资产平衡项目": "current_assets.balance_items",
    
    # Assets - Non Current
    "非流动资产合计": "non_current_assets.total_non_current_assets",
    "发放贷款及垫款": "non_current_assets.loans_and_advances",
    "债权投资": "non_current_assets.debt_investments",
    "其他债权投资": "non_current_assets.other_debt_investments",
    "长期应收款": "non_current_assets.long_term_receivables",
    "长期股权投资": "non_current_assets.long_term_equity_investments",
    "投资性房地产": "non_current_assets.investment_properties",
    "固定资产": "non_current_assets.fixed_assets",
    "在建工程": "non_current_assets.construction_in_progress",
    "工程物资": "non_current_assets.construction_materials",
    "其他权益工具投资": "non_current_assets.other_equity_instrument_investments",
    "其他非流动金融资产": "non_current_assets.other_non_current_financial_assets",
    "固定资产清理": "non_current_assets.fixed_assets_liquidation",
    "生产性生物资产": "non_current_assets.productive_biological_assets",
    "油气资产": "non_current_assets.oil_and_gas_assets",
    "使用权资产": "non_current_assets.right_of_use_assets",
    "无形资产": "non_current_assets.intangible_assets",
    "开发支出": "non_current_assets.development_expenses",
    "商誉": "non_current_assets.goodwill",
    "长期待摊费用": "non_current_assets.long_term_deferred_expenses",
    "递延所得税资产": "non_current_assets.deferred_tax_assets",
    "其他非流动资产": "non_current_assets.other_non_current_assets",
    "以摊余成本计量的金融资产(非流动)": "non_current_assets.financial_assets_amortized_cost_non_current",
    "以公允价值计量且其变动计入其他综合收益的金融资产(非流动)": "non_current_assets.financial_assets_fvoci_non_current",
    "可供出售金融资产": "non_current_assets.available_for_sale_financial_assets",
    "持有至到期投资": "non_current_assets.held_to_maturity_investments",
    "非流动资产平衡项目": "non_current_assets.balance_items",
    "非流动资产其他项目": "non_current_assets.other_items",
    
    # Total Assets
    "资产总计": "assets_summary.total_assets",
    "资产其他项目": "assets_summary.other_asset_items",
    "资产平衡项目": "assets_summary.asset_balance_items",

    # Liabilities - Current
    "流动负债合计": "current_liabilities.total_current_liabilities",
    "短期借款": "current_liabilities.short_term_borrowings",
    "向中央银行借款": "current_liabilities.borrowings_from_central_bank",
    "吸收存款及同业存放": "current_liabilities.deposits_and_interbank_placements",
    "拆入资金": "current_liabilities.borrowings_from_interbank",
    "交易性金融负债": "current_liabilities.financial_liabilities_fvpl.trading_financial_liabilities",
    "其中:交易性金融负债": "current_liabilities.financial_liabilities_fvpl.trading_financial_liabilities",
    "其中:指定以公允价值计量且其变动计入当期损益的金融负债": "current_liabilities.financial_liabilities_fvpl.designated_financial_liabilities_fvpl",
    "衍生金融负债": "current_liabilities.derivative_financial_liabilities",
    "应付票据": "current_liabilities.notes_and_accounts_payable.notes_payable",
    "应付账款": "current_liabilities.notes_and_accounts_payable.accounts_payable",
    "应付票据及应付账款": "current_liabilities.notes_and_accounts_payable.amount",
    "预收款项": "current_liabilities.advances_from_customers",
    "合同负债": "current_liabilities.contract_liabilities",
    "卖出回购金融资产款": "current_liabilities.sell_buy_back_financial_assets",
    "应付手续费及佣金": "current_liabilities.fees_and_commissions_payable",
    "应付职工薪酬": "current_liabilities.payroll_payable",
    "应交税费": "current_liabilities.taxes_payable",
    "应付利息": "current_liabilities.other_payables_total.interest_payable",
    "其中:应付利息": "current_liabilities.other_payables_total.interest_payable",
    "应付股利": "current_liabilities.other_payables_total.dividends_payable",
    "其中:应付股利": "current_liabilities.other_payables_total.dividends_payable",
    "其他应付款": "current_liabilities.other_payables_total.amount",
    "其中:其他应付款": "current_liabilities.other_payables_total.other_payables",
    "其他应付款合计": "current_liabilities.other_payables_total.amount",
    "应付分保账款": "current_liabilities.reinsurance_accounts_payable",
    "内部应付款": "current_liabilities.internal_payables",
    "预计流动负债": "current_liabilities.estimated_current_liabilities",
    "保险合同准备金": "current_liabilities.insurance_contract_reserves",
    "代理买卖证券款": "current_liabilities.acting_trading_securities",
    "代理承销证券款": "current_liabilities.acting_underwriting_securities",
    "一年内的递延收益": "current_liabilities.deferred_revenue_within_1y",
    "以摊余成本计量的金融负债": "current_liabilities.financial_liabilities_amortized_cost",
    "应付短期债券": "current_liabilities.short_term_bonds_payable",
    "划分为持有待售的负债": "current_liabilities.liabilities_held_for_sale",
    "一年内到期的非流动负债": "current_liabilities.non_current_liabilities_due_within_1y",
    "代理业务负债": "current_liabilities.agency_business_liabilities",
    "其他流动负债": "current_liabilities.other_current_liabilities",
    "流动负债其他项目": "current_liabilities.other_items",
    "流动负债平衡项目": "current_liabilities.balance_items",

    # Liabilities - Non Current
    "非流动负债合计": "non_current_liabilities.total_non_current_liabilities",
    "长期借款": "non_current_liabilities.long_term_borrowings",
    "以摊余成本计量的金融负债(非流动)": "non_current_liabilities.financial_liabilities_amortized_cost_non_current",
    "应付债券": "non_current_liabilities.bonds_payable.amount",
    "其中:优先股(应付债券)": "non_current_liabilities.bonds_payable.preference_shares",
    "其中:永续债(应付债券)": "non_current_liabilities.bonds_payable.perpetual_bonds",
    "租赁负债": "non_current_liabilities.lease_liabilities",
    "长期应付款": "non_current_liabilities.long_term_payables",
    "长期应付职工薪酬": "non_current_liabilities.long_term_payroll_payable",
    "专项应付款": "non_current_liabilities.special_payables",
    "预计负债": "non_current_liabilities.estimated_liabilities",
    "递延收益": "non_current_liabilities.deferred_revenue",
    "递延收益-非流动负债": "non_current_liabilities.deferred_revenue",
    "递延所得税负债": "non_current_liabilities.deferred_tax_liabilities",
    "其他非流动负债": "non_current_liabilities.other_non_current_liabilities",
    "非流动负债其他项目": "non_current_liabilities.other_items",
    "非流动负债平衡项目": "non_current_liabilities.balance_items",

    # Total Liabilities
    "负债合计": "liabilities_summary.total_liabilities",
    "负债总计": "liabilities_summary.total_liabilities",
    "负债其他项目": "liabilities_summary.other_liability_items",
    "负债平衡项目": "liabilities_summary.liability_balance_items",

    # Equity
    "所有者权益合计": "equity.total_equity",
    "股东权益合计": "equity.total_equity",
    "实收资本(或股本)": "equity.paid_in_capital",
    "实收资本": "equity.paid_in_capital",
    "股本": "equity.paid_in_capital",
    "其他权益工具": "equity.other_equity_instruments.amount",
    "其中:优先股(其他权益工具)": "equity.other_equity_instruments.preference_shares",
    "其中:永续债(其他权益工具)": "equity.other_equity_instruments.perpetual_bonds",
    "其中:其他(其他权益工具)": "equity.other_equity_instruments.other",
    "资本公积": "equity.capital_reserves",
    "资本公积金": "equity.capital_reserves",
    "减:库存股": "equity.treasury_stock",
    "库存股": "equity.treasury_stock",
    "其他综合收益": "equity.other_comprehensive_income",
    "其它综合收益": "equity.other_comprehensive_income",
    "盈余公积": "equity.surplus_reserves",
    "盈余公积金": "equity.surplus_reserves",
    "一般风险准备": "equity.general_risk_reserves",
    "专项储备": "equity.special_reserves",
    "未确定的投资损失": "equity.unconfirmed_investment_loss",
    "未分配利润": "equity.undistributed_profit",
    "拟分配现金股利": "equity.proposed_cash_dividends",
    "外币报表折算差额": "equity.currency_translation_diff",
    "归属于母公司所有者权益合计": "equity.total_parent_equity",
    "归属于母公司股东权益其他项目": "equity.parent_equity_other_items",
    "归属于母公司股东权益平衡项目": "equity.parent_equity_balance_items",
    "少数股东权益": "equity.minority_interests",
    "股东权益其他项目": "equity.equity_other_items",
    "股权权益平衡项目": "equity.equity_balance_items",

    # Total L&E
    "负债和所有者权益总计": "balance_check.total_liabilities_and_equity",
    "负债和股东权益总计": "balance_check.total_liabilities_and_equity",
    "负债和股东权益其他项目": "balance_check.liabilities_and_equity_other_items",
    "负债及股东权益平衡项目": "balance_check.liabilities_and_equity_balance_items",
}

CASH_FLOW_MAP = {
    # Operating Activities
    "经营活动产生的现金流量净额": "operating_activities.net_cash_flow_from_operating",
    "销售商品、提供劳务收到的现金": "operating_activities.cash_received_from_goods_and_services",
    "客户存款和同业存放款项净增加额": "operating_activities.net_increase_deposits_interbank",
    "向中央银行借款净增加额": "operating_activities.net_increase_borrowings_central_bank",
    "向其他金融机构拆入资金净增加额": "operating_activities.net_increase_borrowings_other_financial",
    "收到原保险合同保费取得的现金": "operating_activities.cash_received_original_premiums",
    "收到再保险业务现金净额": "operating_activities.net_cash_received_reinsurance",
    "保户储金及投资款净增加额": "operating_activities.net_increase_insured_investment",
    "处置交易性金融资产净增加额": "operating_activities.net_increase_disposal_trading_assets",
    "收取利息、手续费及佣金的现金": "operating_activities.cash_received_interest_commission",
    "拆入资金净增加额": "operating_activities.net_increase_borrowed_funds",
    "发放贷款及垫款的净减少额": "operating_activities.net_decrease_loans_advances",
    "回购业务资金净增加额": "operating_activities.net_increase_repurchase_funds",
    "收到的税费返还": "operating_activities.tax_refunds_received",
    "收到其他与经营活动有关的现金": "operating_activities.other_cash_received_operating",
    "经营活动现金流入其他项目": "operating_activities.inflow_other_items",
    "经营活动现金流入平衡项目": "operating_activities.inflow_balance_items",
    "经营活动现金流入小计": "operating_activities.subtotal_cash_inflow_operating",
    "购买商品、接受劳务支付的现金": "operating_activities.cash_paid_for_goods_and_services",
    "客户贷款及垫款净增加额": "operating_activities.net_increase_loans_advances",
    "存放中央银行和同业款项净增加额": "operating_activities.net_increase_deposits_central_bank_interbank",
    "支付原保险合同赔付款项的现金": "operating_activities.cash_paid_original_contract_claims",
    "支付利息、手续费及佣金的现金": "operating_activities.cash_paid_interest_commission",
    "支付保单红利的现金": "operating_activities.cash_paid_policy_dividends",
    "支付给职工以及为职工支付的现金": "operating_activities.cash_paid_to_employees",
    "支付的各项税费": "operating_activities.taxes_paid",
    "支付其他与经营活动有关的现金": "operating_activities.other_cash_paid_operating",
    "经营活动现金流出其他项目": "operating_activities.outflow_other_items",
    "经营活动现金流出平衡项目": "operating_activities.outflow_balance_items",
    "经营活动现金流出小计": "operating_activities.subtotal_cash_outflow_operating",
    "经营活动产生的现金流量净额其他项目": "operating_activities.net_cash_flow_other_items",
    "经营活动现金流量净额平衡项目": "operating_activities.net_cash_flow_balance_items",

    # Investing Activities
    "投资活动产生的现金流量净额": "investing_activities.net_cash_flow_from_investing",
    "收回投资收到的现金": "investing_activities.cash_received_from_investment_recovery",
    "取得投资收益收到的现金": "investing_activities.cash_received_from_investment_income",
    "处置固定资产、无形资产和其他长期资产收回的现金净额": "investing_activities.net_cash_from_disposal_assets",
    "处置子公司及其他营业单位收到的现金净额": "investing_activities.net_cash_from_disposal_subsidiaries",
    "减少质押和定期存款所收到的现金": "investing_activities.cash_received_from_pledge_deposit_reduction",
    "收到其他与投资活动有关的现金": "investing_activities.other_cash_received_investing",
    "投资活动现金流入其他项目": "investing_activities.inflow_other_items",
    "投资活动现金流入平衡项目": "investing_activities.inflow_balance_items",
    "投资活动现金流入小计": "investing_activities.subtotal_cash_inflow_investing",
    "购建固定资产、无形资产和其他长期资产支付的现金": "investing_activities.cash_paid_for_assets",
    "投资支付的现金": "investing_activities.cash_paid_for_investments",
    "质押贷款净增加额": "investing_activities.net_increase_pledged_loans",
    "取得子公司及其他营业单位支付的现金净额": "investing_activities.net_cash_paid_subsidiaries",
    "增加质押和定期存款所支付的现金": "investing_activities.cash_paid_for_pledge_deposit_increase",
    "支付其他与投资活动有关的现金": "investing_activities.other_cash_paid_investing",
    "投资活动现金流出其他项目": "investing_activities.outflow_other_items",
    "投资活动现金流出平衡项目": "investing_activities.outflow_balance_items",
    "投资活动现金流出小计": "investing_activities.subtotal_cash_outflow_investing",
    "投资活动产生的现金流量净额其他项目": "investing_activities.net_cash_flow_other_items",
    "投资活动产生的现金流量净额平衡项目": "investing_activities.net_cash_flow_balance_items",

    # Financing Activities
    "筹资活动产生的现金流量净额": "financing_activities.net_cash_flow_from_financing",
    "吸收投资收到的现金": "financing_activities.cash_received_from_investments.amount",
    "其中:子公司吸收少数股东投资收到的现金": "financing_activities.cash_received_from_investments.from_minority_shareholders",
    "取得借款收到的现金": "financing_activities.cash_received_from_borrowings",
    "发行债券收到的现金": "financing_activities.cash_received_from_bond_issue",
    "收到其他与筹资活动有关的现金": "financing_activities.other_cash_received_financing",
    "筹资活动现金流入其他项目": "financing_activities.inflow_other_items",
    "筹资活动现金流入平衡项目": "financing_activities.inflow_balance_items",
    "筹资活动现金流入小计": "financing_activities.subtotal_cash_inflow_financing",
    "偿还债务支付的现金": "financing_activities.cash_paid_for_debt_repayment",
    "分配股利、利润或偿付利息支付的现金": "financing_activities.cash_paid_for_dividends_and_profits",
    "其中:子公司支付给少数股东的股利、利润": "financing_activities.dividends_paid_to_minority",
    "购买子公司少数股权而支付的现金": "financing_activities.cash_paid_for_minority_equity",
    "支付其他与筹资活动有关的现金": "financing_activities.other_cash_paid_financing.amount",
    "其中：子公司减资支付给少数股东的现金": "financing_activities.other_cash_paid_financing.paid_to_minority_for_capital_reduction",
    "筹资活动现金流出其他项目": "financing_activities.outflow_other_items",
    "筹资活动现金流出平衡项目": "financing_activities.outflow_balance_items",
    "筹资活动现金流出小计": "financing_activities.subtotal_cash_outflow_financing",
    "筹资活动产生的现金流量净额其他项目": "financing_activities.net_cash_flow_other_items",
    "筹资活动产生的现金流量净额平衡项目": "financing_activities.net_cash_flow_balance_items",

    # Overall Cash Change
    "汇率变动对现金及现金等价物的影响": "cash_increase.exchange_rate_effect",
    "汇率变动对现金的影响": "cash_increase.exchange_rate_effect",
    "现金及现金等价物净增加额其他项目": "cash_increase.increase_other_items",
    "现金及现金等价物净增加额平衡项目": "cash_increase.increase_balance_items",
    "现金及现金等价物净增加额": "cash_increase.net_increase_cash_and_equivalents",
    "期初现金及现金等价物余额": "cash_increase.cash_at_beginning",
    "期末现金及现金等价物余额其他项目": "cash_increase.end_balance_other_items",
    "期末现金及现金等价物余额平衡项目": "cash_increase.end_balance_balance_items",
    "期末现金及现金等价物余额": "cash_increase.cash_at_end",

    # Supplementary Info
    "净利润": "supplementary_info.net_profit_adjustment.net_profit",
    "资产减值准备": "supplementary_info.net_profit_adjustment.asset_impairment_reserves",
    "固定资产和投资性房地产折旧": "supplementary_info.net_profit_adjustment.depreciation_fixed_assets_investment_props", 
    "固定资产折旧、油气资产折耗、生产性生物资产折旧": "supplementary_info.net_profit_adjustment.depreciation_others", # Fixed mapping
    "其中:固定资产折旧": "supplementary_info.net_profit_adjustment.depreciation_others", # Synonym
    "投资性房地产折旧摊销": "supplementary_info.net_profit_adjustment.depreciation_investment_props",
    "无形资产摊销": "supplementary_info.net_profit_adjustment.amortization_intangible_assets",
    "长期待摊费用摊销": "supplementary_info.net_profit_adjustment.amortization_long_term_deferred",
    "递延收益摊销": "supplementary_info.net_profit_adjustment.amortization_deferred_revenue",
    "待摊费用的减少": "supplementary_info.net_profit_adjustment.decrease_deferred_expenses",
    "预提费用的增加": "supplementary_info.net_profit_adjustment.increase_accrued_expenses",
    "处置固定资产、无形资产和其他长期资产的损失": "supplementary_info.net_profit_adjustment.loss_disposal_assets",
    "固定资产报废损失": "supplementary_info.net_profit_adjustment.loss_scrapping_assets",
    "公允价值变动损失": "supplementary_info.net_profit_adjustment.loss_fair_value_change",
    "财务费用": "supplementary_info.net_profit_adjustment.financial_expenses",
    "投资损失": "supplementary_info.net_profit_adjustment.investment_loss",
    "递延所得税": "supplementary_info.net_profit_adjustment.deferred_tax",
    "递延所得税资产减少": "supplementary_info.net_profit_adjustment.decrease_deferred_tax_assets",
    "递延所得税负债增加": "supplementary_info.net_profit_adjustment.increase_deferred_tax_liabilities",
    "预计负债的增加": "supplementary_info.net_profit_adjustment.increase_estimated_liabilities",
    "存货的减少": "supplementary_info.net_profit_adjustment.decrease_inventories",
    "经营性应收项目的减少": "supplementary_info.net_profit_adjustment.decrease_operating_receivables",
    "经营性应付项目的增加": "supplementary_info.net_profit_adjustment.increase_operating_payables",
    "其他": "supplementary_info.net_profit_adjustment.other",
    "经营活动现金流量净额(补充)": "supplementary_info.net_profit_adjustment.net_cash_flow_from_operating_indirect",
    
    "债务转为资本": "supplementary_info.significant_non_cash.debt_to_capital",
    "一年内到期的可转换公司债券": "supplementary_info.significant_non_cash.convertible_bonds_due_within_1y",
    "融资租入固定资产": "supplementary_info.significant_non_cash.fixed_assets_finance_lease",
    "不涉及现金收支的投资和筹资活动金额其他项目": "supplementary_info.significant_non_cash.non_cash_items_other",
    
    "现金的期末余额": "supplementary_info.cash_change_check.cash_end_balance",
    "现金的期初余额": "supplementary_info.cash_change_check.cash_begin_balance",
    "现金等价物的期末余额": "supplementary_info.cash_change_check.equivalents_end_balance",
    "现金等价物的期初余额": "supplementary_info.cash_change_check.equivalents_begin_balance",
    "现金及现金等价物净增加额其他项目": "supplementary_info.cash_change_check.net_increase_other",
    "现金及现金等价物净增加额平衡项目": "supplementary_info.cash_change_check.net_increase_balance",
    "现金及现金等价物净增加额(补充)": "supplementary_info.cash_change_check.net_increase_cash_and_equivalents_indirect",
}
